class CreatePlayerStats < ActiveRecord::Migration[7.0]
  def change
    create_table :player_stats do |t|
      t.belongs_to :user
      t.integer :player_time
      t.integer :player_time_0h
      t.integer :player_time_10h
      t.integer :player_time_20h
      t.integer :player_time_40h
      t.integer :player_time_80h
      t.integer :player_time_100h
      t.integer :player_time_150h
      t.integer :player_time_200h
      t.integer :player_time_250h
      t.integer :player_time_500h
      t.integer :player_time_1000h
      t.integer :player_level
      t.integer :player_level_0
      t.integer :player_level_10
      t.integer :player_level_20
      t.integer :player_level_30
      t.integer :player_level_40
      t.integer :player_level_50
      t.integer :player_level_60
      t.integer :player_level_70
      t.integer :player_level_80
      t.integer :player_level_90
      t.integer :player_level_100
      t.integer :player_cash
      t.integer :player_cash_0k
      t.integer :player_cash_1k
      t.integer :player_cash_10k
      t.integer :player_cash_100k
      t.integer :player_cash_1000k
      t.integer :player_cash_10000k
      t.integer :player_cash_100000k
      t.integer :player_cash_1000000k
      t.integer :player_cash_10000000k
      t.integer :player_cash_100000000k
      t.integer :player_cash_1000000000k
      t.integer :skill_mastermind
      t.integer :skill_mastermind_0
      t.integer :skill_mastermind_5
      t.integer :skill_mastermind_10
      t.integer :skill_mastermind_15
      t.integer :skill_mastermind_20
      t.integer :skill_mastermind_25
      t.integer :skill_mastermind_30
      t.integer :skill_mastermind_35
      t.integer :skill_enforcer
      t.integer :skill_enforcer_0
      t.integer :skill_enforcer_5
      t.integer :skill_enforcer_10
      t.integer :skill_enforcer_15
      t.integer :skill_enforcer_20
      t.integer :skill_enforcer_25
      t.integer :skill_enforcer_30
      t.integer :skill_enforcer_35
      t.integer :skill_technician
      t.integer :skill_technician_0
      t.integer :skill_technician_5
      t.integer :skill_technician_10
      t.integer :skill_technician_15
      t.integer :skill_technician_20
      t.integer :skill_technician_25
      t.integer :skill_technician_30
      t.integer :skill_technician_35
      t.integer :skill_ghost
      t.integer :skill_ghost_0
      t.integer :skill_ghost_5
      t.integer :skill_ghost_10
      t.integer :skill_ghost_15
      t.integer :skill_ghost_20
      t.integer :skill_ghost_25
      t.integer :skill_ghost_30
      t.integer :skill_ghost_35
      t.integer :skill_mastermind_cable_guy
      t.integer :skill_mastermind_cable_guy_ace
      t.integer :skill_mastermind_combat_medic
      t.integer :skill_mastermind_combat_medic_ace
      t.integer :skill_mastermind_triathlete
      t.integer :skill_mastermind_triathlete_ace
      t.integer :skill_mastermind_inside_man
      t.integer :skill_mastermind_inside_man_ace
      t.integer :skill_mastermind_fast_learner
      t.integer :skill_mastermind_fast_learner_ace
      t.integer :skill_mastermind_leadership
      t.integer :skill_mastermind_leadership_ace
      t.integer :skill_mastermind_tactician
      t.integer :skill_mastermind_tactician_ace
      t.integer :skill_mastermind_equilibrium
      t.integer :skill_mastermind_equilibrium_ace
      t.integer :skill_mastermind_dominator
      t.integer :skill_mastermind_dominator_ace
      t.integer :skill_mastermind_stockholm_syndrome
      t.integer :skill_mastermind_stockholm_syndrome_ace
      t.integer :skill_mastermind_medic_2x
      t.integer :skill_mastermind_medic_2x_ace
      t.integer :skill_mastermind_joker
      t.integer :skill_mastermind_joker_ace
      t.integer :skill_mastermind_black_marketeer
      t.integer :skill_mastermind_black_marketeer_ace
      t.integer :skill_mastermind_gun_fighter
      t.integer :skill_mastermind_gun_fighter_ace
      t.integer :skill_mastermind_kilmer
      t.integer :skill_mastermind_kilmer_ace
      t.integer :skill_mastermind_control_freak
      t.integer :skill_mastermind_control_freak_ace
      t.integer :skill_mastermind_pistol_messiah
      t.integer :skill_mastermind_pistol_messiah_ace
      t.integer :skill_mastermind_inspire
      t.integer :skill_mastermind_inspire_ace
      t.integer :skill_enforcer_oppressor
      t.integer :skill_enforcer_oppressor_ace
      t.integer :skill_enforcer_ammo_reservoir
      t.integer :skill_enforcer_ammo_reservoir_ace
      t.integer :skill_enforcer_pack_mule
      t.integer :skill_enforcer_pack_mule_ace
      t.integer :skill_enforcer_show_of_force
      t.integer :skill_enforcer_show_of_force_ace
      t.integer :skill_enforcer_underdog
      t.integer :skill_enforcer_underdog_ace
      t.integer :skill_enforcer_steroids
      t.integer :skill_enforcer_steroids_ace
      t.integer :skill_enforcer_shotgun_impact
      t.integer :skill_enforcer_shotgun_impact_ace
      t.integer :skill_enforcer_shades
      t.integer :skill_enforcer_shades_ace
      t.integer :skill_enforcer_tough_guy
      t.integer :skill_enforcer_tough_guy_ace
      t.integer :skill_enforcer_shotgun_cqb
      t.integer :skill_enforcer_shotgun_cqb_ace
      t.integer :skill_enforcer_ammo_2x
      t.integer :skill_enforcer_ammo_2x_ace
      t.integer :skill_enforcer_wolverine
      t.integer :skill_enforcer_wolverine_ace
      t.integer :skill_enforcer_from_the_hip
      t.integer :skill_enforcer_from_the_hip_ace
      t.integer :skill_enforcer_bandoliers
      t.integer :skill_enforcer_bandoliers_ace
      t.integer :skill_enforcer_portable_saw
      t.integer :skill_enforcer_portable_saw_ace
      t.integer :skill_enforcer_overkill
      t.integer :skill_enforcer_overkill_ace
      t.integer :skill_enforcer_juggernaut
      t.integer :skill_enforcer_juggernaut_ace
      t.integer :skill_enforcer_carbon_blade
      t.integer :skill_enforcer_carbon_blade_ace
      t.integer :skill_technician_rifleman
      t.integer :skill_technician_rifleman_ace
      t.integer :skill_technician_trip_miner
      t.integer :skill_technician_trip_miner_ace
      t.integer :skill_technician_discipline
      t.integer :skill_technician_discipline_ace
      t.integer :skill_technician_sharpshooter
      t.integer :skill_technician_sharpshooter_ace
      t.integer :skill_technician_trip_mine_expert
      t.integer :skill_technician_trip_mine_expert_ace
      t.integer :skill_technician_hardware_expert
      t.integer :skill_technician_hardware_expert_ace
      t.integer :skill_technician_sentry_gun
      t.integer :skill_technician_sentry_gun_ace
      t.integer :skill_technician_master_craftsman
      t.integer :skill_technician_master_craftsman_ace
      t.integer :skill_technician_drill_expert
      t.integer :skill_technician_drill_expert_ace
      t.integer :skill_technician_sentry_targeting_package
      t.integer :skill_technician_sentry_targeting_package_ace
      t.integer :skill_technician_blast_radius
      t.integer :skill_technician_blast_radius_ace
      t.integer :skill_technician_silent_drilling
      t.integer :skill_technician_silent_drilling_ace
      t.integer :skill_technician_sentry_2_0
      t.integer :skill_technician_sentry_2_0_ace
      t.integer :skill_technician_shaped_charge
      t.integer :skill_technician_shaped_charge_ace
      t.integer :skill_technician_insulation
      t.integer :skill_technician_insulation_ace
      t.integer :skill_technician_sentry_gun_2x
      t.integer :skill_technician_sentry_gun_2x_ace
      t.integer :skill_technician_mag_plus
      t.integer :skill_technician_mag_plus_ace
      t.integer :skill_technician_iron_man
      t.integer :skill_technician_iron_man_ace
      t.integer :skill_ghost_scavenger
      t.integer :skill_ghost_scavenger_ace
      t.integer :skill_ghost_sprinter
      t.integer :skill_ghost_sprinter_ace
      t.integer :skill_ghost_cat_burglar
      t.integer :skill_ghost_cat_burglar_ace
      t.integer :skill_ghost_transporter
      t.integer :skill_ghost_transporter_ace
      t.integer :skill_ghost_chameleon
      t.integer :skill_ghost_chameleon_ace
      t.integer :skill_ghost_cleaner
      t.integer :skill_ghost_cleaner_ace
      t.integer :skill_ghost_assassin
      t.integer :skill_ghost_assassin_ace
      t.integer :skill_ghost_martial_arts
      t.integer :skill_ghost_martial_arts_ace
      t.integer :skill_ghost_smg_master
      t.integer :skill_ghost_smg_master_ace
      t.integer :skill_ghost_nine_lives
      t.integer :skill_ghost_nine_lives_ace
      t.integer :skill_ghost_ecm_2x
      t.integer :skill_ghost_ecm_2x_ace
      t.integer :skill_ghost_hitman
      t.integer :skill_ghost_hitman_ace
      t.integer :skill_ghost_magic_touch
      t.integer :skill_ghost_magic_touch_ace
      t.integer :skill_ghost_ecm_booster
      t.integer :skill_ghost_ecm_booster_ace
      t.integer :skill_ghost_silence_expert
      t.integer :skill_ghost_silence_expert_ace
      t.integer :skill_ghost_good_luck_charm
      t.integer :skill_ghost_good_luck_charm_ace
      t.integer :skill_ghost_ecm_feedback
      t.integer :skill_ghost_ecm_feedback_ace
      t.integer :skill_ghost_moving_target
      t.integer :skill_ghost_moving_target_ace
      t.integer :mask_used_gagball
      t.integer :mask_used_mummy
      t.integer :mask_used_mr_sinister
      t.integer :mask_used_cthulhu
      t.integer :mask_used_hog
      t.integer :mask_used_skull
      t.integer :mask_used_scarecrow
      t.integer :mask_used_bullet
      t.integer :mask_used_alienware
      t.integer :mask_used_dripper
      t.integer :mask_used_dallas_clean
      t.integer :mask_used_oni
      t.integer :mask_used_anonymous
      t.integer :mask_used_outlandish_a
      t.integer :mask_used_outlandish_b
      t.integer :mask_used_outlandish_c
      t.integer :mask_used_jaw
      t.integer :mask_used_dallas
      t.integer :mask_used_grin
      t.integer :mask_used_tounge
      t.integer :mask_used_shogun
      t.integer :mask_used_day_of_the_dead
      t.integer :mask_used_demon
      t.integer :mask_used_hockey
      t.integer :mask_used_biglips
      t.integer :mask_used_troll
      t.integer :mask_used_buha
      t.integer :mask_used_vampire
      t.integer :mask_used_character_locked
      t.integer :mask_used_chains
      t.integer :mask_used_demonictender
      t.integer :mask_used_zombie
      t.integer :mask_used_dillinger_death_mask
      t.integer :mask_used_brainiack
      t.integer :mask_used_shrunken
      t.integer :mask_used_stonekisses
      t.integer :mask_used_clown_56
      t.integer :mask_used_greek_tragedy
      t.integer :mask_used_monkeybiss
      t.integer :mask_used_wolf
      t.integer :mask_used_wolf_clean
      t.integer :mask_used_dawn_of_the_dead
      t.integer :mask_used_hoxton_clean
      t.integer :mask_used_chains_clean
      t.integer :mask_used_zipper
      t.integer :mask_used_clowncry
      t.integer :mask_used_hoxton
      t.integer :mask_used_babyrhino
      t.integer :mask_used_irondoom
      t.integer :mask_used_rubber_male
      t.integer :mask_used_rubber_female
      t.integer :mask_used_pumpkin_king
      t.integer :mask_used_witch
      t.integer :mask_used_venomorph
      t.integer :mask_used_frank
      t.integer :mask_used_brazil_baby
      t.integer :mask_used_baby_angry
      t.integer :mask_used_baby_cry
      t.integer :mask_used_baby_happy
      t.integer :mask_used_heat
      t.integer :mask_used_bear
      t.integer :mask_used_clinton
      t.integer :mask_used_bush
      t.integer :mask_used_obama
      t.integer :mask_used_nixon
      t.integer :mask_used_kawaii
      t.integer :mask_used_goat
      t.integer :mask_used_panda
      t.integer :mask_used_pitbull
      t.integer :mask_used_eagle
      t.integer :mask_used_santa_happy
      t.integer :mask_used_santa_mad
      t.integer :mask_used_santa_drunk
      t.integer :mask_used_santa_surprise
      t.integer :mask_used_aviator
      t.integer :mask_used_ghost
      t.integer :mask_used_welder
      t.integer :mask_used_plague
      t.integer :mask_used_smoker
      t.integer :mask_used_cloth_commander
      t.integer :mask_used_gage_blade
      t.integer :mask_used_gage_rambo
      t.integer :mask_used_gage_deltaforce
      t.integer :mask_used_skullhard
      t.integer :mask_used_skullveryhard
      t.integer :mask_used_skulloverkill
      t.integer :mask_used_skulloverkillplus
      t.integer :player_rank_0
      t.integer :player_rank_1
      t.integer :player_rank_2
      t.integer :player_rank_3
      t.integer :player_rank_4
      t.integer :player_rank_5
      t.integer :mask_used_samurai
      t.integer :mask_used_twitch_orc
      t.integer :mask_used_ancient
      t.integer :mask_used_metalhead
      t.integer :mask_used_tcn
      t.integer :mask_used_surprise
      t.integer :mask_used_optimist_prime
      t.integer :mask_used_franklin
      t.integer :mask_used_lincoln
      t.integer :mask_used_grant
      t.integer :mask_used_washington
      t.integer :mask_used_mantis
      t.integer :mask_used_wasp
      t.integer :mask_used_robberfly
      t.integer :mask_used_spider
      t.integer :mask_used_silverback
      t.integer :mask_used_mandril
      t.integer :mask_used_skullmonkey
      t.integer :mask_used_orangutang
      t.integer :skill_mastermind_unlocked
      t.integer :skill_enforcer_unlocked
      t.integer :skill_technician_unlocked
      t.integer :skill_ghost_unlocked
      t.integer :mask_used_unicorn
      t.integer :mask_used_galax
      t.integer :mask_used_crowgoblin
      t.integer :mask_used_evil
      t.integer :mask_used_volt
      t.integer :mask_used_white_wolf
      t.integer :mask_used_owl
      t.integer :mask_used_rabbit
      t.integer :mask_used_pig
      t.integer :mask_used_panther
      t.integer :mask_used_rooster
      t.integer :mask_used_horse
      t.integer :mask_used_tiger
      t.integer :mask_used_stoneface
      t.integer :mask_used_wayfarer
      t.integer :mask_used_combusto
      t.integer :mask_used_spackle
      t.integer :mask_used_smiley
      t.integer :mask_used_gumbo
      t.integer :mask_used_crazy_lion
      t.integer :mask_used_old_hoxton
      t.integer :skill_hoxton
      t.integer :skill_hoxton_0
      t.integer :skill_hoxton_5
      t.integer :skill_hoxton_10
      t.integer :skill_hoxton_15
      t.integer :skill_hoxton_20
      t.integer :skill_hoxton_25
      t.integer :skill_hoxton_30
      t.integer :skill_hoxton_35
      t.integer :skill_hoxton_unlocked
      t.integer :skill_hoxton_freedom_call
      t.integer :skill_hoxton_freedom_call_ace
      t.integer :skill_hoxton_hidden_blade
      t.integer :skill_hoxton_hidden_blade_ace
      t.integer :skill_hoxton_thick_skin
      t.integer :skill_hoxton_thick_skin_ace
      t.integer :skill_hoxton_awareness
      t.integer :skill_hoxton_awareness_ace
      t.integer :skill_hoxton_jail_workout
      t.integer :skill_hoxton_jail_workout_ace
      t.integer :skill_hoxton_alpha_dog
      t.integer :skill_hoxton_alpha_dog_ace
      t.integer :skill_hoxton_cell_mates
      t.integer :skill_hoxton_cell_mates_ace
      t.integer :skill_hoxton_thug_life
      t.integer :skill_hoxton_thug_life_ace
      t.integer :skill_hoxton_tea_time
      t.integer :skill_hoxton_tea_time_ace
      t.integer :skill_hoxton_perseverance
      t.integer :skill_hoxton_perseverance_ace
      t.integer :skill_hoxton_second_chances
      t.integer :skill_hoxton_second_chances_ace
      t.integer :skill_hoxton_tea_cookies
      t.integer :skill_hoxton_tea_cookies_ace
      t.integer :skill_hoxton_trigger_happy
      t.integer :skill_hoxton_trigger_happy_ace
      t.integer :skill_hoxton_backstab
      t.integer :skill_hoxton_backstab_ace
      t.integer :skill_hoxton_drop_soap
      t.integer :skill_hoxton_drop_soap_ace
      t.integer :skill_hoxton_prison_wife
      t.integer :skill_hoxton_prison_wife_ace
      t.integer :skill_hoxton_jail_diet
      t.integer :skill_hoxton_jail_diet_ace
      t.integer :skill_hoxton_akimbo
      t.integer :skill_hoxton_akimbo_ace
      t.integer :mask_used_the_one_below
      t.integer :mask_used_lycan
      t.integer :mask_used_churchill
      t.integer :mask_used_red_hurricane
      t.integer :mask_used_patton
      t.integer :mask_used_de_gaulle
      t.integer :mask_used_area51
      t.integer :mask_used_alien_helmet
      t.integer :mask_used_krampus
      t.integer :mask_used_mrs_claus
      t.integer :mask_used_strinch
      t.integer :mask_used_robo_santa
      t.integer :mask_used_almirs_beard
      t.integer :mask_used_msk_grizel
      t.integer :mask_used_medusa
      t.integer :mask_used_anubis
      t.integer :mask_used_pazuzu
      t.integer :mask_used_cursed_crown
      t.integer :mask_used_nun_town
      t.integer :mask_used_robo_arnold
      t.integer :mask_used_arch_nemesis
      t.integer :mask_used_grizel_clean
      t.integer :mask_used_champion_dallas
      t.integer :mask_used_dragan
      t.integer :mask_used_dragan_begins
      t.integer :mask_used_butcher
      t.integer :mask_used_doctor
      t.integer :mask_used_tech_lion
      t.integer :mask_used_lady_butcher
      t.integer :mask_used_carnotaurus
      t.integer :mask_used_triceratops
      t.integer :mask_used_pachy
      t.integer :mask_used_velociraptor
      t.integer :mask_used_jake
      t.integer :mask_used_richter
      t.integer :mask_used_biker
      t.integer :mask_used_alex
      t.integer :mask_used_corey
      t.integer :mask_used_tonys_revenge
      t.integer :mask_used_richard_returns
      t.integer :mask_used_richard_begins
      t.integer :mask_used_the_overkill_mask
      t.integer :mask_used_dallas_glow
      t.integer :mask_used_wolf_glow
      t.integer :mask_used_hoxton_glow
      t.integer :mask_used_chains_glow
      t.integer :mask_used_bonnie
      t.integer :mask_used_bonnie_begins
      t.integer :player_rank_6
      t.integer :player_rank_7
      t.integer :player_rank_8
      t.integer :player_rank_9
      t.integer :player_rank_10
      t.integer :player_rank_11
      t.integer :player_rank_12
      t.integer :player_rank_13
      t.integer :player_rank_14
      t.integer :player_rank_15
      t.integer :player_rank_16
      t.integer :player_rank_17
      t.integer :player_rank_18
      t.integer :player_rank_19
      t.integer :player_rank_20
      t.integer :player_rank_21
      t.integer :player_rank_22
      t.integer :player_rank_23
      t.integer :player_rank_24
      t.integer :player_rank_25
      t.integer :mask_used_simpson
      t.integer :player_specialization_1
      t.integer :player_specialization_2
      t.integer :player_specialization_3
      t.integer :player_specialization_4
      t.integer :player_specialization_5
      t.integer :player_specialization_6
      t.integer :player_specialization_7
      t.integer :player_specialization_8
      t.integer :player_specialization_9
      t.integer :player_specialization_10
      t.integer :mask_used_hothead
      t.integer :mask_used_falcon
      t.integer :mask_used_unic
      t.integer :mask_used_speedrunner
      t.integer :mask_used_hectors_helmet
      t.integer :mask_used_old_hoxton_begins
      t.integer :player_specialization_active
      t.integer :mask_used_firedemon
      t.integer :mask_used_gasmask
      t.integer :mask_used_firemask
      t.integer :mask_used_chef_hat
      t.integer :mask_used_bandit
      t.integer :mask_used_bullskull
      t.integer :mask_used_kangee
      t.integer :mask_used_lone
      t.integer :mask_used_grendel
      t.integer :mask_used_concert_male
      t.integer :mask_used_concert_female
      t.integer :mask_used_boombox
      t.integer :mask_used_cantus
      t.integer :mask_used_titan
      t.integer :mask_used_pokachu
      t.integer :mask_used_moon
      t.integer :mask_used_borsuk
      t.integer :mask_used_card_jack
      t.integer :mask_used_card_queen
      t.integer :mask_used_card_king
      t.integer :mask_used_card_joker
      t.integer :mask_used_sokol
      t.integer :mask_used_sokol_begins
      t.integer :mask_used_croupier_hat
      t.integer :mask_used_gladiator_helmet
      t.integer :mask_used_the_king_mask
      t.integer :mask_used_sports_utility_mask
      t.integer :mask_used_starvr
      t.integer :player_specialization_11
      t.integer :mask_used_jw_shades
      t.integer :mask_used_destroyer
      t.integer :mask_used_punk
      t.integer :mask_used_pain
      t.integer :mask_used_infamy_lurker
      t.integer :mask_used_daft
      t.integer :mask_used_ranger
      t.integer :mask_used_infamy_hood
      t.integer :mask_used_balaclava
      t.integer :mask_used_ninja_hood
      t.integer :mask_used_shirai
      t.integer :mask_used_kage
      t.integer :mask_used_slicer
      t.integer :mask_used_bobblehead_dozer
      t.integer :player_specialization_12
      t.integer :mask_used_jiro
      t.integer :mask_used_jiro_begins
      t.integer :mask_used_king_of_jesters
      t.integer :player_specialization_13
      t.integer :mask_used_mason_vanguard_veteran
      t.integer :mask_used_agatha_knight
      t.integer :mask_used_agatha_vanguard_veteran
      t.integer :mask_used_mason_knight_veteran
      t.integer :mask_used_vlad_armor
      t.integer :mask_used_sputnik
      t.integer :mask_used_tiara
      t.integer :mask_used_rus_hat
      t.integer :mask_used_baba_yaga
      t.integer :mask_used_lcv
      t.integer :mask_used_oliver
      t.integer :mask_used_eggian
      t.integer :mask_used_fatboy
      t.integer :mask_used_pirate_skull
      t.integer :mask_used_glasses_tinted_love
      t.integer :mask_used_groucho_glasses
      t.integer :mask_used_rageface
      t.integer :mask_used_dawg
      t.integer :mask_used_baitface
      t.integer :mask_used_nomegusta
      t.integer :mask_used_satan
      t.integer :mask_used_invader
      t.integer :mask_used_tormentor
      t.integer :mask_used_bodhi
      t.integer :mask_used_bodhi_begins
      t.integer :mask_used_oro
      t.integer :mask_used_water_spirit
      t.integer :mask_used_maui
      t.integer :mask_used_tane
      t.integer :mask_used_rudeolph
      t.integer :mask_used_greedy_the_elf
      t.integer :mask_used_goat_goat
      t.integer :mask_used_fancy_goat
      t.integer :mask_used_tall_goat
      t.integer :mask_used_wet_goat
      t.integer :mask_used_unborn
      t.integer :mask_used_devourer
      t.integer :mask_used_divided
      t.integer :mask_used_viking
      t.integer :mask_used_nutcracker
      t.integer :mask_used_horned_king
      t.integer :mask_used_hunter
      t.integer :mask_used_megacthulhu
      t.integer :mask_used_cop_skull
      t.integer :mask_used_cop_plague_doctor
      t.integer :mask_used_cop_kawaii
      t.integer :player_specialization_14
      t.integer :mask_used_jimmy
      t.integer :mask_used_jimmy_duct
      t.integer :mask_used_mad_mask
      t.integer :mask_used_half_mask
      t.integer :mask_used_mad_goggles
      t.integer :mask_used_visor
      t.integer :mask_used_dbd_slasher
      t.integer :player_specialization_15
      t.integer :mask_used_sydney
      t.integer :mask_used_sydney_begins
      t.integer :mask_used_solus
      t.integer :mask_used_dbd_01
      t.integer :mask_used_dbd_02
      t.integer :mask_used_dbd_03
      t.integer :mask_used_dbd_04
      t.integer :skill_mastermind_tea_time
      t.integer :skill_mastermind_tea_time_ace
      t.integer :skill_mastermind_tea_cookies
      t.integer :skill_mastermind_tea_cookies_ace
      t.integer :skill_mastermind_stable_shot
      t.integer :skill_mastermind_stable_shot_ace
      t.integer :skill_mastermind_rifleman
      t.integer :skill_mastermind_rifleman_ace
      t.integer :skill_mastermind_sharpshooter
      t.integer :skill_mastermind_sharpshooter_ace
      t.integer :skill_mastermind_spotter_teamwork
      t.integer :skill_mastermind_spotter_teamwork_ace
      t.integer :skill_mastermind_speedy_reload
      t.integer :skill_mastermind_speedy_reload_ace
      t.integer :skill_mastermind_single_shot_ammo_return
      t.integer :skill_mastermind_single_shot_ammo_return_ace
      t.integer :skill_enforcer_far_away
      t.integer :skill_enforcer_far_away_ace
      t.integer :skill_enforcer_close_by
      t.integer :skill_enforcer_close_by_ace
      t.integer :skill_enforcer_iron_man
      t.integer :skill_enforcer_iron_man_ace
      t.integer :skill_enforcer_prison_wife
      t.integer :skill_enforcer_prison_wife_ace
      t.integer :skill_enforcer_scavenging
      t.integer :skill_enforcer_scavenging_ace
      t.integer :skill_technician_defense_up
      t.integer :skill_technician_defense_up_ace
      t.integer :skill_technician_eco_sentry
      t.integer :skill_technician_eco_sentry_ace
      t.integer :skill_technician_engineering
      t.integer :skill_technician_engineering_ace
      t.integer :skill_technician_jack_of_all_trades
      t.integer :skill_technician_jack_of_all_trades_ace
      t.integer :skill_technician_tower_defense
      t.integer :skill_technician_tower_defense_ace
      t.integer :skill_technician_combat_engineering
      t.integer :skill_technician_combat_engineering_ace
      t.integer :skill_technician_more_fire_power
      t.integer :skill_technician_more_fire_power_ace
      t.integer :skill_technician_kick_starter
      t.integer :skill_technician_kick_starter_ace
      t.integer :skill_technician_fire_trap
      t.integer :skill_technician_fire_trap_ace
      t.integer :skill_technician_steady_grip
      t.integer :skill_technician_steady_grip_ace
      t.integer :skill_technician_heavy_impact
      t.integer :skill_technician_heavy_impact_ace
      t.integer :skill_technician_fire_control
      t.integer :skill_technician_fire_control_ace
      t.integer :skill_technician_shock_and_awe
      t.integer :skill_technician_shock_and_awe_ace
      t.integer :skill_technician_fast_fire
      t.integer :skill_technician_fast_fire_ace
      t.integer :skill_technician_body_expertise
      t.integer :skill_technician_body_expertise_ace
      t.integer :skill_ghost_jail_workout
      t.integer :skill_ghost_jail_workout_ace
      t.integer :skill_ghost_second_chances
      t.integer :skill_ghost_second_chances_ace
      t.integer :skill_ghost_awareness
      t.integer :skill_ghost_awareness_ace
      t.integer :skill_ghost_thick_skin
      t.integer :skill_ghost_thick_skin_ace
      t.integer :skill_ghost_dire_need
      t.integer :skill_ghost_dire_need_ace
      t.integer :skill_ghost_insulation
      t.integer :skill_ghost_insulation_ace
      t.integer :skill_ghost_jail_diet
      t.integer :skill_ghost_jail_diet_ace
      t.integer :skill_ghost_optic_illusions
      t.integer :skill_ghost_optic_illusions_ace
      t.integer :skill_ghost_backstab
      t.integer :skill_ghost_backstab_ace
      t.integer :skill_ghost_unseen_strike
      t.integer :skill_ghost_unseen_strike_ace
      t.integer :skill_hoxton_equilibrium
      t.integer :skill_hoxton_equilibrium_ace
      t.integer :skill_hoxton_dance_instructor
      t.integer :skill_hoxton_dance_instructor_ace
      t.integer :skill_hoxton_gun_fighter
      t.integer :skill_hoxton_gun_fighter_ace
      t.integer :skill_hoxton_expert_handling
      t.integer :skill_hoxton_expert_handling_ace
      t.integer :skill_hoxton_nine_lives
      t.integer :skill_hoxton_nine_lives_ace
      t.integer :skill_hoxton_running_from_death
      t.integer :skill_hoxton_running_from_death_ace
      t.integer :skill_hoxton_up_you_go
      t.integer :skill_hoxton_up_you_go_ace
      t.integer :skill_hoxton_feign_death
      t.integer :skill_hoxton_feign_death_ace
      t.integer :skill_hoxton_messiah
      t.integer :skill_hoxton_messiah_ace
      t.integer :skill_hoxton_martial_arts
      t.integer :skill_hoxton_martial_arts_ace
      t.integer :skill_hoxton_bloodthirst
      t.integer :skill_hoxton_bloodthirst_ace
      t.integer :skill_hoxton_steroids
      t.integer :skill_hoxton_steroids_ace
      t.integer :skill_hoxton_wolverine
      t.integer :skill_hoxton_wolverine_ace
      t.integer :skill_hoxton_frenzy
      t.integer :skill_hoxton_frenzy_ace
      t.integer :mask_used_jig_01
      t.integer :mask_used_jig_02
      t.integer :mask_used_damned
      t.integer :player_specialization_16
      t.integer :mask_used_born_biker_01
      t.integer :mask_used_born_biker_02
      t.integer :mask_used_born_biker_03
      t.integer :mask_used_brutal
      t.integer :mask_used_rust
      t.integer :mask_used_rust_begins
      t.integer :mask_used_mig_war
      t.integer :mask_used_cop_mega_gage_blade
      t.integer :mask_used_mig_famine
      t.integer :mask_used_mig_conquest
      t.integer :mask_used_mig_death
      t.integer :mask_used_fab_mega_mark
      t.integer :mask_used_fab_mega_alien
      t.integer :mask_used_fab_mega_doctor
      t.integer :mask_used_fab_mega_grin
      t.integer :mask_used_nyck_pickle
      t.integer :mask_used_gti_al_capone
      t.integer :mask_used_gti_bugsy
      t.integer :mask_used_urf_seal
      t.integer :mask_used_gti_lucky_luciano
      t.integer :mask_used_fib_mouse
      t.integer :mask_used_nyck_beret
      t.integer :mask_used_nyck_ace
      t.integer :mask_used_spk_party
      t.integer :mask_used_fib_hare
      t.integer :mask_used_gti_madame_st_claire
      t.integer :mask_used_fib_cat
      t.integer :mask_used_fib_fox
      t.integer :mask_used_nyck_cap
      t.integer :mask_used_gitgud_e_wish
      t.integer :mask_used_gitgud_sm_wish
      t.integer :mask_used_pim_russian_ballistic
      t.integer :mask_used_pim_dog
      t.integer :mask_used_pim_mustang
      t.integer :mask_used_pim_hotelier
      t.integer :mask_used_howl_chains_zombie
      t.integer :mask_used_hwl_dallas_zombie
      t.integer :mask_used_hwl_hoxton_zombie
      t.integer :mask_used_hwl_wolf_zombie
      t.integer :mask_used_pdc16_clover
      t.integer :mask_used_tng_cap
      t.integer :mask_used_tng_zeal_swat_mask
      t.integer :mask_used_tng_cloaker
      t.integer :mask_used_tng_bandana
      t.integer :mask_used_win_donald
      t.integer :mask_used_win_donald_mega
      t.integer :mask_used_moon_paycheck_chains
      t.integer :mask_used_moon_paycheck_dallas
      t.integer :player_coins
      t.integer :player_coins_0
      t.integer :player_coins_24
      t.integer :player_coins_48
      t.integer :player_coins_72
      t.integer :player_coins_96
      t.integer :player_coins_120
      t.integer :player_coins_144
      t.integer :player_coins_168
      t.integer :player_coins_192
      t.integer :player_coins_216
      t.integer :player_coins_240
      t.integer :player_coins_264
      t.integer :player_coins_288
      t.integer :player_coins_312
      t.integer :player_coins_336
      t.integer :player_coins_360
      t.integer :player_coins_384
      t.integer :player_coins_408
      t.integer :player_coins_432
      t.integer :player_coins_456
      t.integer :player_coins_480
      t.integer :player_coins_500
      t.integer :player_coins_600
      t.integer :player_coins_700
      t.integer :player_coins_800
      t.integer :player_coins_900
      t.integer :player_coins_1000
      t.integer :mask_used_chc_terry
      t.integer :mask_used_chc_terry_begins
      t.integer :mask_used_sfm_01
      t.integer :mask_used_sfm_02
      t.integer :mask_used_sfm_03
      t.integer :mask_used_sfm_04
      t.integer :mask_used_sha_01
      t.integer :mask_used_sha_02
      t.integer :mask_used_sha_03
      t.integer :mask_used_sha_04
      t.integer :mask_used_swm_sydney
      t.integer :mask_used_spa_01
      t.integer :mask_used_spa_02
      t.integer :mask_used_spa_03
      t.integer :mask_used_spa_04
      t.integer :mask_used_yor
      t.integer :mask_used_grv_01
      t.integer :mask_used_grv_02
      t.integer :mask_used_grv_03
      t.integer :mask_used_grv_04
      t.integer :mask_used_grv_01_bodhi
      t.integer :mask_used_grv_01_bonnie
      t.integer :mask_used_bny_01
      t.integer :mask_used_bny_02
      t.integer :mask_used_bny_03
      t.integer :mask_used_bny_04
      t.integer :mask_used_bny_01_bonnie
      t.integer :mask_used_bny_01_clover
      t.integer :mask_used_bny_01_clover_b
      t.integer :mask_used_bny_01_bodhi
      t.integer :mask_used_bny_02_clover
      t.integer :mask_used_bny_02_bonnie
      t.integer :mask_used_bny_02_bodhi
      t.integer :mask_used_bny_03_clover
      t.integer :mask_used_bny_03_bodhi
      t.integer :mask_used_mp2_01
      t.integer :mask_used_mp2_02
      t.integer :mask_used_mp2_03
      t.integer :mask_used_mp2_04
      t.integer :mask_used_mrm
      t.integer :mask_used_amp_01
      t.integer :mask_used_amp_02
      t.integer :mask_used_amp_03
      t.integer :mask_used_amp_04
      t.integer :player_specialization_17
      t.integer :player_specialization_18
      t.integer :mask_used_mdm
      t.integer :mask_used_max
      t.integer :mask_used_max_begins
      t.integer :mask_used_ant_01
      t.integer :mask_used_ant_02
      t.integer :mask_used_ant_03
      t.integer :mask_used_ant_04
      t.integer :mask_used_ant_05
      t.integer :mask_used_ant_06
      t.integer :mask_used_ant_07
      t.integer :mask_used_ant_08
      t.integer :mask_used_dgm
      t.integer :mask_used_eng_01
      t.integer :mask_used_eng_02
      t.integer :mask_used_eng_03
      t.integer :mask_used_eng_04
      t.integer :mask_used_jfr_01
      t.integer :mask_used_jfr_02
      t.integer :mask_used_jfr_03
      t.integer :mask_used_jfr_04
      t.integer :mask_used_wmp_01
      t.integer :mask_used_wmp_02
      t.integer :mask_used_wmp_03
      t.integer :mask_used_wmp_04
      t.integer :mask_used_cmo_01
      t.integer :mask_used_cmo_02
      t.integer :mask_used_cmo_03
      t.integer :mask_used_cmo_04
      t.integer :mask_used_dnm
      t.integer :mask_used_kwm
      t.integer :mask_used_mmj
      t.integer :mask_used_myh
      t.integer :mask_used_sds_01
      t.integer :mask_used_sds_04
      t.integer :mask_used_sds_05
      t.integer :mask_used_sds_07
      t.integer :mask_used_sds_02
      t.integer :mask_used_sds_03
      t.integer :mask_used_sds_06
      t.integer :mask_used_pbm
      t.integer :mask_used_myh_begins
      t.integer :mask_used_fdm
      t.integer :player_specialization_19
      t.integer :mask_used_gcm
      t.integer :player_specialization_20
      t.integer :mask_used_ecp_female
      t.integer :mask_used_ecp_female_begins
      t.integer :mask_used_ecp_male
      t.integer :mask_used_ecp_male_begins
      t.integer :mask_used_rvd_1
      t.integer :mask_used_rvd_2
      t.integer :mask_used_rvd_3
      t.integer :mask_used_cmt_01
      t.integer :mask_used_cmt_02
      t.integer :mask_used_cmt_03
      t.integer :mask_used_cmt_04
      t.integer :mask_used_rvd_01
      t.integer :mask_used_rvd_02
      t.integer :mask_used_rvd_03
      t.integer :mask_used_ami_01
      t.integer :mask_used_ami_02
      t.integer :mask_used_ami_03
      t.integer :mask_used_ami_04
      t.integer :mask_used_ami_05
      t.integer :mask_used_ami_06
      t.integer :mask_used_flm
      t.integer :mask_used_ggac_od_t2
      t.integer :mask_used_mmh
      t.integer :mask_used_sdm_01
      t.integer :mask_used_sdm_02
      t.integer :mask_used_sdm_03
      t.integer :mask_used_sdm_04
      t.integer :mask_used_tam
      t.integer :mask_used_toon_01
      t.integer :mask_used_toon_02
      t.integer :mask_used_toon_03
      t.integer :mask_used_toon_04
      t.integer :mask_used_ztm
      t.integer :player_specialization_21
      t.integer :mask_used_ghm
      t.integer :mask_used_ghx
      t.integer :mask_used_gwm
      t.integer :mask_used_joy
      t.integer :mask_used_joy_begins
      t.integer :mask_used_maw_01
      t.integer :mask_used_skm_01
      t.integer :mask_used_skm_02
      t.integer :mask_used_skm_03
      t.integer :mask_used_skm_04
      t.integer :mask_used_skm_05
      t.integer :mask_used_skm_06
      t.integer :mask_used_skm_07
      t.integer :mask_used_skm_08
      t.integer :mask_used_smo_01
      t.integer :mask_used_smo_02
      t.integer :mask_used_smo_03
      t.integer :mask_used_smo_04
      t.integer :mask_used_smo_05
      t.integer :mask_used_smo_06
      t.integer :mask_used_smo_07
      t.integer :mask_used_smo_08
      t.integer :mask_used_smo_09
      t.integer :mask_used_smo_10
      t.integer :mask_used_smo_11
      t.integer :mask_used_smo_12
      t.integer :mask_used_smo_big_02
      t.integer :mask_used_smo_common_02
      t.integer :mask_used_smo_hila_02
      t.integer :mask_used_sms_01
      t.integer :mask_used_sms_02
      t.integer :mask_used_sms_03
      t.integer :mask_used_sms_04
      t.integer :mask_used_sms_05
      t.integer :mask_used_sms_06
      t.integer :mask_used_sms_07
      t.integer :mask_used_sms_08
      t.integer :mask_used_roman
      t.integer :mask_used_scm_01
      t.integer :mask_used_scm_02
      t.integer :suit_used_jail_pd2_clan
      t.integer :suit_used_murky_suit
      t.integer :suit_used_raincoat
      t.integer :suit_used_scrub
      t.integer :suit_used_sneak_suit
      t.integer :suit_used_tux
      t.integer :suit_used_winter_suit
      t.integer :suit_used_clown_white
      t.integer :suit_used_clown_red
      t.integer :suit_used_clown_black_and_white
      t.integer :suit_used_clown_black
      t.integer :suit_used_jumpsuit_default
      t.integer :suit_used_jumpsuit_red
      t.integer :suit_used_jumpsuit_green
      t.integer :suit_used_jumpsuit_brown
      t.integer :suit_used_jumpsuit_blue
      t.integer :suit_used_miami_default
      t.integer :suit_used_miami_white
      t.integer :suit_used_miami_grey
      t.integer :suit_used_miami_black
      t.integer :suit_used_peacoat_default
      t.integer :suit_used_peacoat_white
      t.integer :suit_used_peacoat_brown
      t.integer :suit_used_peacoat_blue
      t.integer :suit_used_peacoat_black
      t.integer :suit_used_clown_default
      t.integer :suit_used_none
      t.integer :suit_used_miami_pink
      t.integer :mask_used_sombrero
      t.integer :suit_used_mariachi_default
      t.integer :suit_used_mariachi_white
      t.integer :suit_used_mariachi_red
      t.integer :suit_used_mariachi_black
      t.integer :suit_used_poolrepair_default
      t.integer :suit_used_xmas_tuxedo_green
      t.integer :suit_used_xmas_tuxedo_black
      t.integer :suit_used_desperado_default
      t.integer :suit_used_desperado_white
      t.integer :suit_used_desperado_green
      t.integer :suit_used_desperado_blue
      t.integer :suit_used_hiphop_white
      t.integer :suit_used_hiphop_green
      t.integer :suit_used_hippie_default
      t.integer :suit_used_hippie_native
      t.integer :suit_used_hippie_abstraction
      t.integer :suit_used_punk_default
      t.integer :suit_used_punk_red
      t.integer :suit_used_punk_blue
      t.integer :suit_used_punk_billieboy
      t.integer :suit_used_punk_scottish
      t.integer :suit_used_hippie_flowerpower
      t.integer :suit_used_hippie_tribe
      t.integer :suit_used_hiphop_beige
      t.integer :suit_used_hiphop_red
      t.integer :suit_used_hiphop_default
      t.integer :suit_used_desperado_red
      t.integer :suit_used_xmas_tuxedo_blue
      t.integer :suit_used_xmas_tuxedo_default
      t.integer :suit_used_mariachi_brown
      t.integer :suit_used_slaughterhouse
      t.integer :suit_used_esport_yellow
      t.integer :suit_used_esport_green
      t.integer :suit_used_esport_default
      t.integer :suit_used_esport_black
      t.integer :player_rank_26
      t.integer :player_rank_27
      t.integer :player_rank_28
      t.integer :player_rank_29
      t.integer :player_rank_30
      t.integer :player_rank_31
      t.integer :player_rank_32
      t.integer :player_rank_34
      t.integer :player_rank_36
      t.integer :player_rank_37
      t.integer :player_rank_39
      t.integer :player_rank_41
      t.integer :player_rank_43
      t.integer :player_rank_44
      t.integer :player_rank_45
      t.integer :player_rank_46
      t.integer :player_rank_47
      t.integer :player_rank_48
      t.integer :player_rank_49
      t.integer :player_rank_51
      t.integer :player_rank_52
      t.integer :player_rank_54
      t.integer :player_rank_56
      t.integer :player_rank_57
      t.integer :player_rank_58
      t.integer :player_rank_59
      t.integer :player_rank_60
      t.integer :player_rank_61
      t.integer :player_rank_62
      t.integer :player_rank_63
      t.integer :player_rank_64
      t.integer :player_rank_65
      t.integer :player_rank_66
      t.integer :player_rank_67
      t.integer :player_rank_68
      t.integer :player_rank_69
      t.integer :player_rank_70
      t.integer :player_rank_71
      t.integer :player_rank_72
      t.integer :player_rank_73
      t.integer :player_rank_74
      t.integer :player_rank_75
      t.integer :player_rank_76
      t.integer :player_rank_77
      t.integer :player_rank_78
      t.integer :player_rank_79
      t.integer :player_rank_80
      t.integer :player_rank_81
      t.integer :player_rank_82
      t.integer :player_rank_83
      t.integer :player_rank_84
      t.integer :player_rank_85
      t.integer :player_rank_86
      t.integer :player_rank_87
      t.integer :player_rank_88
      t.integer :player_rank_89
      t.integer :player_rank_90
      t.integer :player_rank_91
      t.integer :player_rank_92
      t.integer :player_rank_93
      t.integer :player_rank_94
      t.integer :player_rank_95
      t.integer :player_rank_96
      t.integer :player_rank_97
      t.integer :player_rank_98
      t.integer :player_rank_99
      t.integer :player_rank_100
      t.integer :player_rank_200
      t.integer :player_rank_300
      t.integer :player_rank_350
      t.integer :player_rank_400
      t.integer :player_rank_450
      t.integer :mask_used_buluc
      t.integer :mask_used_uno_01
      t.integer :suit_used_continental
      t.integer :suit_used_cartelboss
      t.integer :suit_used_esport_white
      t.integer :suit_used_gentleman_veteran
      t.integer :suit_used_gentleman_marine
      t.integer :suit_used_gentleman_father
      t.integer :suit_used_gunslinger_red
      t.integer :suit_used_gunslinger_piro
      t.integer :suit_used_gunslinger_casual
      t.integer :suit_used_t800_default
      t.integer :suit_used_t800_toughboy
      t.integer :suit_used_t800_red
      t.integer :suit_used_t800_cowboy
      t.integer :player_rank_500
      t.integer :suit_used_gunslinger_default
      t.integer :suit_used_gentleman_default
      t.integer :player_rank_250
      t.integer :player_rank_150
      t.integer :player_rank_55
      t.integer :player_rank_53
      t.integer :player_rank_50
      t.integer :player_rank_42
      t.integer :player_rank_40
      t.integer :player_rank_38
      t.integer :player_rank_35
      t.integer :player_rank_33
      t.integer :mask_used_biden
      t.integer :mask_used_cyberpunk
      t.integer :mask_used_lastlaugh
      t.integer :mask_used_mega_max
      t.integer :mask_used_msq_02
      t.integer :mask_used_msq_04
      t.integer :mask_used_xm20_jaguar
      t.integer :mask_used_xm20_owl
      t.integer :mask_used_xm20_serpent
      t.integer :suit_used_candycane
      t.integer :suit_used_leather_white
      t.integer :suit_used_leather_black
      t.integer :mask_used_msq_01
      t.integer :mask_used_msq_03
      t.integer :mask_used_xm20_dog
      t.integer :suit_used_badsanta
      t.integer :suit_used_leather_default
      t.integer :suit_used_leather_red
      t.integer :mask_used_daemon
      t.integer :mask_used_dragon01
      t.integer :mask_used_dragon02
      t.integer :mask_used_godess
      t.integer :suit_used_thug_default
      t.integer :suit_used_hitman_red
      t.integer :suit_used_hitman_brown
      t.integer :suit_used_hitman_blue
      t.integer :suit_used_traditional_default
      t.integer :suit_used_traditional_red
      t.integer :suit_used_traditional_brown
      t.integer :suit_used_traditional_blue
      t.integer :suit_used_hitman_default
      t.integer :mask_used_goldenbrute
      t.integer :mask_used_ingoldnito
      t.integer :suit_used_gangstercoat_default
      t.integer :suit_used_gangstercoat_irish
      t.integer :suit_used_gangstercoat_french
      t.integer :suit_used_gangstercoat_british
      t.integer :suit_used_general_default
      t.integer :suit_used_general_white
      t.integer :suit_used_general_red
      t.integer :suit_used_general_blue
      t.integer :suit_used_poolrepair_electric
      t.integer :suit_used_poolrepair
      t.integer :suit_used_cable_guy
      t.integer :mask_used_boss
      t.integer :suit_used_boss
      t.integer :mask_used_blacktortoise
      t.integer :mask_used_vermilionbird
      t.integer :mask_used_whitetiger
      t.integer :suit_used_highinttech_default
      t.integer :suit_used_highinttech_green
      t.integer :suit_used_lowinttech_default
      t.integer :suit_used_lowinttech_red
      t.integer :mask_used_azuredragon
      t.integer :suit_used_thug_black
      t.integer :suit_used_highinttech_orange
      t.integer :suit_used_highinttech_blue
      t.integer :suit_used_lowinttech_yellow
      t.integer :suit_used_lowinttech_blue
      t.integer :mask_used_eighthgrin
      t.integer :suit_used_baron_default
      t.integer :suit_used_baron_blue
      t.integer :mask_used_mnk
      t.integer :mask_used_mnt
      t.integer :mask_used_tgr
      t.integer :mask_used_vpr
      t.integer :suit_used_cyberhoodie_default
      t.integer :suit_used_cyberhoodie_mnt
      t.integer :suit_used_cybertrench_default
      t.integer :suit_used_cybertrench_mnt
      t.integer :suit_used_cybertrench_tgr
      t.integer :suit_used_cyberhoodie_vpr
      t.integer :suit_used_cybertrench_vpr
      t.integer :suit_used_cyberhoodie_tgr
      t.integer :player_rank
      t.integer :suit_used_thug_red
      t.integer :mask_used_jesterskulls
      t.integer :suit_used_clown_2_default
      t.integer :suit_used_clown_2_yellow
      t.integer :suit_used_clown_2_white
      t.integer :suit_used_clown_2_orange
      t.integer :mask_used_tophatske
      t.integer :mask_used_tophatskeblue
      t.integer :mask_used_tophatskered
      t.integer :suit_used_classyske_default
      t.integer :suit_used_classyske_red
      t.integer :suit_used_classyske_cream
      t.integer :mask_used_elegantteeth
      t.integer :mask_used_overkillpunk
      t.integer :suit_used_elegantscarf
      t.integer :suit_used_overkillpunk
      t.integer :player_specialization_22
      t.integer :mask_used_foxfurhat
      t.integer :mask_used_icedeer
      t.integer :mask_used_iceskull
      t.integer :mask_used_leshy
      t.integer :suit_used_lonorwa_default
      t.integer :suit_used_lonorwa_white
      t.integer :suit_used_lonorwa_orange
      t.integer :suit_used_lonorwa_blue
      t.integer :suit_used_rusbear_default
      t.integer :suit_used_rusbear_quilt
      t.integer :suit_used_rusbear_blacmor
      t.integer :suit_used_rusbear_arctic
      t.integer :mask_used_trol
      t.integer :mask_used_hockeynermark
      t.integer :suit_used_bunny
      t.integer :suit_used_sparkle
      t.integer :suit_used_waistcoat
      t.integer :mask_used_biker_helmet_red_led
      t.integer :mask_used_biker_helmet_yellow_led
      t.integer :mask_used_boss_gold
      t.integer :mask_used_boss_silver
      t.integer :mask_used_yufuhelmet
      t.integer :suit_used_kungfumaster_default
      t.integer :suit_used_kungfumaster_white
      t.integer :suit_used_kungfumaster_red
      t.integer :suit_used_kungfumaster_black
      t.integer :suit_used_thug_white
      t.integer :suit_used_boss_default
      t.integer :suit_used_boss_yellow
      t.integer :suit_used_boss_red
      t.integer :suit_used_boss_green
      t.integer :suit_used_enforcer_default
      t.integer :suit_used_enforcer_red_dragon
      t.integer :suit_used_enforcer_dragon
      t.integer :suit_used_enforcer_blood
      t.integer :mask_used_ranchcap_emblem
      t.integer :mask_used_ranchcap_plain
      t.integer :mask_used_ranchcap_texas
      t.integer :mask_used_saloondarklea
      t.integer :mask_used_saloonlightlea
      t.integer :mask_used_saloonstar
      t.integer :suit_used_fighterpilot
      t.integer :suit_used_boss_gdtp_default
      t.integer :suit_used_boss_gdtp_red
      t.integer :suit_used_bullranch_default
      t.integer :suit_used_bullranch_blue
      t.integer :suit_used_texvest_green
      t.integer :suit_used_texvest_blue
      t.integer :suit_used_texvest_black
      t.integer :suit_used_boss_gdtp_yellow
      t.integer :suit_used_boss_gdtp_green
      t.integer :suit_used_bullranch_brown
      t.integer :suit_used_bullranch_black
      t.integer :suit_used_texvest_default
      t.integer :mask_used_saloonshade
      t.integer :mask_used_oilbaron
      t.integer :mask_used_primtime
      t.integer :suit_used_mocow
      t.integer :suit_used_newhorizon
      t.integer :mask_used_chrodome
      t.integer :mask_used_daredev
      t.integer :mask_used_funguy
      t.integer :mask_used_funguy_default
      t.integer :mask_used_funguy_hair
      t.integer :mask_used_speedfreak
      t.integer :mask_used_threap
      t.integer :mask_used_threap_default
      t.integer :mask_used_threap_hair
      t.integer :mask_used_waytexas
      t.integer :suit_used_bikerjacket_default
      t.integer :suit_used_bikerjacket_red
      t.integer :suit_used_bikerjacket_green
      t.integer :suit_used_bikerjacket_gray
      t.integer :suit_used_bikervest_default
      t.integer :suit_used_bikervest_white
      t.integer :suit_used_bikervest_red
      t.integer :suit_used_bikervest_camo
      t.integer :mask_used_skulldia
      t.integer :suit_used_moneysuit_default
      t.integer :suit_used_moneysuit_money
      t.integer :mask_used_megaskulldia
      t.integer :suit_used_moneysuit_gold
      t.integer :mask_used_dodhat
      t.integer :suit_used_dodsuit
      t.integer :mask_used_homburg
      t.integer :mask_used_homburg_grey
      t.integer :mask_used_railhat
      t.integer :suit_used_railroad
      t.integer :suit_used_corl
      t.integer :suit_used_nightwalker
      t.integer :suit_used_ghostly
      t.integer :suit_used_darkprince
      t.integer :mask_used_devilhorn
      t.integer :mask_used_deadman
      t.integer :mask_used_bloodysnarl
      t.integer :mask_used_banshee
      t.integer :mask_used_bandcap_dark
      t.integer :mask_used_flapcapban
      t.integer :mask_used_gentgla_brown
      t.integer :mask_used_gentgla_dark
      t.integer :mask_used_hatgla_dark
      t.integer :mask_used_hatgla_green
      t.integer :suit_used_cargocasual_default
      t.integer :suit_used_cargocasual_texas
      t.integer :suit_used_cargocasual_monke
      t.integer :suit_used_cargocasual_cassette
      t.integer :suit_used_leatherfluff_default
      t.integer :suit_used_leatherfluff_lightning
      t.integer :suit_used_leatherfluff_dots
      t.integer :suit_used_leatherfluff_bats
      t.integer :suit_used_puffervest_default
      t.integer :suit_used_puffervest_red
      t.integer :suit_used_puffervest_grey
      t.integer :suit_used_puffervest_blue
      t.integer :player_specialization_23
      t.integer :mask_used_elfhat
      t.integer :mask_used_elfhat_red
      t.integer :mask_used_elfhat_violet
      t.integer :mask_used_elfhat_yellow
      t.integer :suit_used_elfsuit_default
      t.integer :suit_used_elfsuit_yellow
      t.integer :suit_used_elfsuit_violet
      t.integer :suit_used_elfsuit_red
      t.integer :mask_used_smilecigar
      t.integer :suit_used_sleekygent
      t.integer :mask_used_bthekidmask
      t.integer :mask_used_cassidymask
      t.integer :mask_used_jessjamesmask
      t.integer :mask_used_sambassmask
      t.integer :suit_used_bthekid
      t.integer :suit_used_cassidy
      t.integer :suit_used_jessjames
      t.integer :suit_used_sambass
      t.timestamps
    end
  end
end
