class CreateWeaponStats < ActiveRecord::Migration[7.0]
  def change
    create_table :weapon_stats do |t|
      t.belongs_to :user
      t.integer :weapon_used_new_m4
      t.integer :weapon_used_glock_18c
      t.integer :weapon_used_amcar
      t.integer :weapon_used_m16
      t.integer :weapon_used_olympic
      t.integer :weapon_used_ak74
      t.integer :weapon_used_akm
      t.integer :weapon_used_akmsu
      t.integer :weapon_used_saiga
      t.integer :weapon_used_ak5
      t.integer :weapon_used_aug
      t.integer :weapon_used_g36
      t.integer :weapon_used_p90
      t.integer :weapon_used_new_m14
      t.integer :weapon_used_mp9
      t.integer :weapon_used_deagle
      t.integer :weapon_used_new_mp5
      t.integer :weapon_used_colt_1911
      t.integer :weapon_used_mac10
      t.integer :weapon_used_serbu
      t.integer :weapon_used_r870
      t.integer :weapon_used_glock_17
      t.integer :weapon_used_b92fs
      t.integer :weapon_used_huntsman
      t.integer :weapon_used_new_raging_bull
      t.integer :weapon_used_saw
      t.integer :weapon_used_m45
      t.integer :weapon_used_s552
      t.integer :weapon_used_ppk
      t.integer :weapon_used_usp
      t.integer :weapon_used_mp7
      t.integer :weapon_used_scar
      t.integer :weapon_used_p226
      t.integer :weapon_used_hk21
      t.integer :weapon_used_m249
      t.integer :weapon_used_rpk
      t.integer :weapon_used_g22c
      t.integer :weapon_used_m95
      t.integer :weapon_used_msr
      t.integer :weapon_used_r93
      t.integer :weapon_used_fal
      t.integer :weapon_used_benelli
      t.integer :weapon_used_striker
      t.integer :weapon_used_ksg
      t.integer :weapon_used_akm_gold
      t.integer :melee_used_weapon
      t.integer :melee_used_fists
      t.integer :melee_used_kabar
      t.integer :melee_used_rambo
      t.integer :melee_used_gerber
      t.integer :melee_used_kampfmesser
      t.integer :melee_used_brass_knuckles
      t.integer :melee_used_tomahawk
      t.integer :melee_used_baton
      t.integer :melee_used_shovel
      t.integer :melee_used_becker
      t.integer :weapon_kills_ak5
      t.integer :weapon_kills_ak74
      t.integer :weapon_kills_akm
      t.integer :weapon_kills_akmsu
      t.integer :weapon_kills_amcar
      t.integer :weapon_kills_aug
      t.integer :weapon_kills_b92fs
      t.integer :weapon_kills_colt_1911
      t.integer :weapon_kills_deagle
      t.integer :weapon_kills_g22c
      t.integer :weapon_kills_g36
      t.integer :weapon_kills_glock_17
      t.integer :weapon_kills_glock_18c
      t.integer :weapon_kills_huntsman
      t.integer :weapon_kills_m16
      t.integer :weapon_kills_mac10
      t.integer :weapon_kills_mp9
      t.integer :weapon_kills_new_m14
      t.integer :weapon_kills_new_m4
      t.integer :weapon_kills_new_mp5
      t.integer :weapon_kills_new_raging_bull
      t.integer :weapon_kills_olympic
      t.integer :weapon_kills_p90
      t.integer :weapon_kills_r870
      t.integer :weapon_kills_saiga
      t.integer :weapon_kills_saw
      t.integer :weapon_kills_serbu
      t.integer :weapon_kills_usp
      t.integer :weapon_kills_m45
      t.integer :weapon_kills_s552
      t.integer :weapon_kills_ppk
      t.integer :weapon_kills_mp7
      t.integer :weapon_kills_scar
      t.integer :weapon_kills_p226
      t.integer :weapon_kills_akm_gold
      t.integer :weapon_kills_hk21
      t.integer :weapon_kills_m249
      t.integer :weapon_kills_rpk
      t.integer :weapon_kills_m95
      t.integer :weapon_kills_msr
      t.integer :weapon_kills_r93
      t.integer :weapon_kills_fal
      t.integer :weapon_kills_benelli
      t.integer :weapon_kills_striker
      t.integer :weapon_kills_ksg
      t.integer :melee_kills_weapon
      t.integer :melee_kills_fists
      t.integer :melee_kills_kabar
      t.integer :melee_kills_rambo
      t.integer :melee_kills_gerber
      t.integer :melee_kills_kampfmesser
      t.integer :melee_kills_brass_knuckles
      t.integer :melee_kills_tomahawk
      t.integer :melee_kills_baton
      t.integer :melee_kills_shovel
      t.integer :melee_kills_becker
      t.integer :weapon_used_judge
      t.integer :weapon_kills_judge
      t.integer :melee_used_moneybundle
      t.integer :melee_kills_moneybundle
      t.integer :melee_used_barbedwire
      t.integer :melee_kills_barbedwire
      t.integer :weapon_used_gre_m79
      t.integer :weapon_kills_gre_m79
      t.integer :weapon_used_g3
      t.integer :weapon_kills_g3
      t.integer :weapon_used_galil
      t.integer :weapon_kills_galil
      t.integer :weapon_used_famas
      t.integer :weapon_kills_famas
      t.integer :melee_used_x46
      t.integer :melee_kills_x46
      t.integer :melee_used_dingdong
      t.integer :melee_kills_dingdong
      t.integer :melee_used_bayonet
      t.integer :melee_kills_bayonet
      t.integer :melee_used_bullseye
      t.integer :melee_kills_bullseye
      t.integer :weapon_used_scorpion
      t.integer :weapon_kills_scorpion
      t.integer :weapon_used_tec9
      t.integer :weapon_kills_tec9
      t.integer :weapon_used_uzi
      t.integer :weapon_kills_uzi
      t.integer :melee_used_baseballbat
      t.integer :melee_kills_baseballbat
      t.integer :melee_used_cleaver
      t.integer :melee_kills_cleaver
      t.integer :melee_used_fireaxe
      t.integer :melee_kills_fireaxe
      t.integer :melee_used_machete
      t.integer :melee_kills_machete
      t.integer :melee_used_briefcase
      t.integer :melee_kills_briefcase
      t.integer :weapon_used_jowi
      t.integer :weapon_kills_jowi
      t.integer :weapon_used_x_1911
      t.integer :weapon_kills_x_1911
      t.integer :weapon_used_x_b92fs
      t.integer :weapon_kills_x_b92fs
      t.integer :weapon_used_x_deagle
      t.integer :weapon_kills_x_deagle
      t.integer :weapon_used_g26
      t.integer :weapon_kills_g26
      t.integer :melee_used_kabartanto
      t.integer :melee_kills_kabartanto
      t.integer :weapon_used_spas12
      t.integer :weapon_kills_spas12
      t.integer :melee_used_toothbrush
      t.integer :melee_kills_toothbrush
      t.integer :melee_used_chef
      t.integer :melee_kills_chef
      t.integer :weapon_used_mg42
      t.integer :weapon_kills_mg42
      t.integer :weapon_used_c96
      t.integer :weapon_kills_c96
      t.integer :weapon_used_sterling
      t.integer :weapon_kills_sterling
      t.integer :weapon_used_mosin
      t.integer :weapon_kills_mosin
      t.integer :melee_used_fairbair
      t.integer :melee_kills_fairbair
      t.integer :melee_used_freedom
      t.integer :melee_kills_freedom
      t.integer :melee_used_model24
      t.integer :melee_kills_model24
      t.integer :melee_used_swagger
      t.integer :melee_kills_swagger
      t.integer :melee_used_alien_maul
      t.integer :melee_kills_alien_maul
      t.integer :weapon_used_m1928
      t.integer :weapon_kills_m1928
      t.integer :weapon_used_l85a2
      t.integer :weapon_kills_l85a2
      t.integer :melee_used_shillelagh
      t.integer :melee_kills_shillelagh
      t.integer :melee_used_boxing_gloves
      t.integer :melee_kills_boxing_gloves
      t.integer :weapon_used_vhs
      t.integer :weapon_kills_vhs
      t.integer :melee_used_meat_cleaver
      t.integer :melee_kills_meat_cleaver
      t.integer :weapon_used_hs2000
      t.integer :weapon_kills_hs2000
      t.integer :weapon_used_cobray
      t.integer :weapon_kills_cobray
      t.integer :melee_used_hammer
      t.integer :melee_kills_hammer
      t.integer :weapon_used_m134
      t.integer :weapon_kills_m134
      t.integer :weapon_used_rpg7
      t.integer :weapon_kills_rpg7
      t.integer :weapon_used_b682
      t.integer :weapon_kills_b682
      t.integer :melee_used_whiskey
      t.integer :melee_kills_whiskey
      t.integer :weapon_used_flamethrower_mk2
      t.integer :weapon_used_m32
      t.integer :weapon_used_aa12
      t.integer :melee_used_fork
      t.integer :melee_used_poker
      t.integer :melee_used_spatula
      t.integer :melee_used_tenderizer
      t.integer :weapon_kills_flamethrower_mk2
      t.integer :weapon_kills_m32
      t.integer :weapon_kills_aa12
      t.integer :melee_kills_fork
      t.integer :melee_kills_poker
      t.integer :melee_kills_spatula
      t.integer :melee_kills_tenderizer
      t.integer :weapon_used_peacemaker
      t.integer :weapon_used_winchester1874
      t.integer :weapon_used_plainsrider
      t.integer :melee_used_scalper
      t.integer :melee_used_mining_pick
      t.integer :melee_used_branding_iron
      t.integer :melee_used_bowie
      t.integer :grenade_used_frag
      t.integer :grenade_used_molotov
      t.integer :grenade_used_dynamite
      t.integer :weapon_kills_peacemaker
      t.integer :weapon_kills_winchester1874
      t.integer :weapon_kills_plainsrider
      t.integer :melee_kills_scalper
      t.integer :melee_kills_mining_pick
      t.integer :melee_kills_branding_iron
      t.integer :melee_kills_bowie
      t.integer :grenade_kills_frag
      t.integer :grenade_kills_molotov
      t.integer :grenade_kills_dynamite
      t.integer :weapon_used_x_g22c
      t.integer :weapon_used_x_g17
      t.integer :weapon_used_x_usp
      t.integer :weapon_used_mateba
      t.integer :weapon_used_asval
      t.integer :weapon_used_sub2000
      t.integer :melee_used_microphone
      t.integer :melee_used_detector
      t.integer :melee_used_micstand
      t.integer :melee_used_oldbaton
      t.integer :melee_used_hockey
      t.integer :melee_used_switchblade
      t.integer :melee_used_taser
      t.integer :melee_used_slot_lever
      t.integer :melee_used_croupier_rake
      t.integer :weapon_kills_x_g22c
      t.integer :weapon_kills_x_g17
      t.integer :weapon_kills_x_usp
      t.integer :weapon_kills_mateba
      t.integer :weapon_kills_asval
      t.integer :weapon_kills_sub2000
      t.integer :melee_kills_microphone
      t.integer :melee_kills_detector
      t.integer :melee_kills_micstand
      t.integer :melee_kills_oldbaton
      t.integer :melee_kills_hockey
      t.integer :melee_kills_switchblade
      t.integer :melee_kills_taser
      t.integer :melee_kills_slot_lever
      t.integer :melee_kills_croupier_rake
      t.integer :weapon_used_saw_secondary
      t.integer :weapon_used_hunter
      t.integer :weapon_used_wa2000
      t.integer :weapon_used_polymer
      t.integer :melee_used_twins
      t.integer :melee_used_tiger
      t.integer :melee_used_fight
      t.integer :melee_used_cqc
      t.integer :grenade_used_wpn_prj_four
      t.integer :weapon_kills_saw_secondary
      t.integer :weapon_kills_hunter
      t.integer :weapon_kills_wa2000
      t.integer :weapon_kills_polymer
      t.integer :melee_kills_twins
      t.integer :melee_kills_tiger
      t.integer :melee_kills_fight
      t.integer :melee_kills_cqc
      t.integer :grenade_kills_wpn_prj_four
      t.integer :weapon_used_arblast
      t.integer :weapon_used_long
      t.integer :weapon_used_frankish
      t.integer :weapon_used_baka
      t.integer :melee_used_sandsteel
      t.integer :melee_used_buck
      t.integer :melee_used_beardy
      t.integer :melee_used_great
      t.integer :melee_used_morning
      t.integer :grenade_used_wpn_prj_ace
      t.integer :grenade_used_wpn_prj_jav
      t.integer :weapon_kills_arblast
      t.integer :weapon_kills_long
      t.integer :weapon_kills_frankish
      t.integer :weapon_kills_baka
      t.integer :melee_kills_sandsteel
      t.integer :melee_kills_buck
      t.integer :melee_kills_beardy
      t.integer :melee_kills_great
      t.integer :melee_kills_morning
      t.integer :grenade_kills_wpn_prj_ace
      t.integer :grenade_kills_wpn_prj_jav
      t.integer :weapon_shots_ak5
      t.integer :weapon_shots_ak74
      t.integer :weapon_shots_akm
      t.integer :weapon_shots_akmsu
      t.integer :weapon_shots_amcar
      t.integer :weapon_shots_aug
      t.integer :weapon_shots_b92fs
      t.integer :weapon_shots_colt_1911
      t.integer :weapon_shots_deagle
      t.integer :weapon_shots_g22c
      t.integer :weapon_shots_g36
      t.integer :weapon_shots_glock_17
      t.integer :weapon_shots_glock_18c
      t.integer :weapon_shots_huntsman
      t.integer :weapon_shots_m16
      t.integer :weapon_shots_mac10
      t.integer :weapon_shots_mp9
      t.integer :weapon_shots_new_m14
      t.integer :weapon_shots_new_m4
      t.integer :weapon_shots_new_mp5
      t.integer :weapon_shots_new_raging_bull
      t.integer :weapon_shots_olympic
      t.integer :weapon_shots_p90
      t.integer :weapon_shots_r870
      t.integer :weapon_shots_saiga
      t.integer :weapon_shots_saw
      t.integer :weapon_shots_saw_secondary
      t.integer :weapon_shots_serbu
      t.integer :weapon_shots_usp
      t.integer :weapon_shots_m45
      t.integer :weapon_shots_s552
      t.integer :weapon_shots_ppk
      t.integer :weapon_shots_mp7
      t.integer :weapon_shots_scar
      t.integer :weapon_shots_p226
      t.integer :weapon_shots_akm_gold
      t.integer :weapon_shots_hk21
      t.integer :weapon_shots_m249
      t.integer :weapon_shots_rpk
      t.integer :weapon_shots_m95
      t.integer :weapon_shots_msr
      t.integer :weapon_shots_r93
      t.integer :weapon_shots_fal
      t.integer :weapon_shots_benelli
      t.integer :weapon_shots_striker
      t.integer :weapon_shots_ksg
      t.integer :weapon_shots_judge
      t.integer :weapon_shots_gre_m79
      t.integer :weapon_shots_g3
      t.integer :weapon_shots_galil
      t.integer :weapon_shots_famas
      t.integer :weapon_shots_scorpion
      t.integer :weapon_shots_tec9
      t.integer :weapon_shots_uzi
      t.integer :weapon_shots_jowi
      t.integer :weapon_shots_x_1911
      t.integer :weapon_shots_x_b92fs
      t.integer :weapon_shots_x_deagle
      t.integer :weapon_shots_g26
      t.integer :weapon_shots_spas12
      t.integer :weapon_shots_mg42
      t.integer :weapon_shots_c96
      t.integer :weapon_shots_sterling
      t.integer :weapon_shots_mosin
      t.integer :weapon_shots_m1928
      t.integer :weapon_shots_l85a2
      t.integer :weapon_shots_vhs
      t.integer :weapon_shots_hs2000
      t.integer :weapon_shots_m134
      t.integer :weapon_shots_rpg7
      t.integer :weapon_shots_cobray
      t.integer :weapon_shots_b682
      t.integer :weapon_shots_x_g22c
      t.integer :weapon_shots_x_g17
      t.integer :weapon_shots_x_usp
      t.integer :weapon_shots_flamethrower_mk2
      t.integer :weapon_shots_m32
      t.integer :weapon_shots_aa12
      t.integer :weapon_shots_peacemaker
      t.integer :weapon_shots_winchester1874
      t.integer :weapon_shots_plainsrider
      t.integer :weapon_shots_mateba
      t.integer :weapon_shots_asval
      t.integer :weapon_shots_sub2000
      t.integer :weapon_shots_hunter
      t.integer :weapon_shots_wa2000
      t.integer :weapon_shots_polymer
      t.integer :weapon_shots_arblast
      t.integer :weapon_shots_long
      t.integer :weapon_shots_frankish
      t.integer :weapon_shots_baka
      t.integer :weapon_hits_ak5
      t.integer :weapon_hits_ak74
      t.integer :weapon_hits_akm
      t.integer :weapon_hits_akmsu
      t.integer :weapon_hits_amcar
      t.integer :weapon_hits_aug
      t.integer :weapon_hits_b92fs
      t.integer :weapon_hits_colt_1911
      t.integer :weapon_hits_deagle
      t.integer :weapon_hits_g22c
      t.integer :weapon_hits_g36
      t.integer :weapon_hits_glock_17
      t.integer :weapon_hits_glock_18c
      t.integer :weapon_hits_huntsman
      t.integer :weapon_hits_m16
      t.integer :weapon_hits_mac10
      t.integer :weapon_hits_mp9
      t.integer :weapon_hits_new_m14
      t.integer :weapon_hits_new_m4
      t.integer :weapon_hits_new_mp5
      t.integer :weapon_hits_new_raging_bull
      t.integer :weapon_hits_olympic
      t.integer :weapon_hits_p90
      t.integer :weapon_hits_r870
      t.integer :weapon_hits_saiga
      t.integer :weapon_hits_saw
      t.integer :weapon_hits_saw_secondary
      t.integer :weapon_hits_serbu
      t.integer :weapon_hits_usp
      t.integer :weapon_hits_m45
      t.integer :weapon_hits_s552
      t.integer :weapon_hits_ppk
      t.integer :weapon_hits_mp7
      t.integer :weapon_hits_scar
      t.integer :weapon_hits_p226
      t.integer :weapon_hits_akm_gold
      t.integer :weapon_hits_hk21
      t.integer :weapon_hits_m249
      t.integer :weapon_hits_rpk
      t.integer :weapon_hits_m95
      t.integer :weapon_hits_msr
      t.integer :weapon_hits_r93
      t.integer :weapon_hits_fal
      t.integer :weapon_hits_benelli
      t.integer :weapon_hits_striker
      t.integer :weapon_hits_ksg
      t.integer :weapon_hits_judge
      t.integer :weapon_hits_gre_m79
      t.integer :weapon_hits_g3
      t.integer :weapon_hits_galil
      t.integer :weapon_hits_famas
      t.integer :weapon_hits_scorpion
      t.integer :weapon_hits_tec9
      t.integer :weapon_hits_uzi
      t.integer :weapon_hits_jowi
      t.integer :weapon_hits_x_1911
      t.integer :weapon_hits_x_b92fs
      t.integer :weapon_hits_x_deagle
      t.integer :weapon_hits_g26
      t.integer :weapon_hits_spas12
      t.integer :weapon_hits_mg42
      t.integer :weapon_hits_c96
      t.integer :weapon_hits_sterling
      t.integer :weapon_hits_mosin
      t.integer :weapon_hits_m1928
      t.integer :weapon_hits_l85a2
      t.integer :weapon_hits_vhs
      t.integer :weapon_hits_hs2000
      t.integer :weapon_hits_m134
      t.integer :weapon_hits_rpg7
      t.integer :weapon_hits_cobray
      t.integer :weapon_hits_b682
      t.integer :weapon_hits_x_g22c
      t.integer :weapon_hits_x_g17
      t.integer :weapon_hits_x_usp
      t.integer :weapon_hits_flamethrower_mk2
      t.integer :weapon_hits_m32
      t.integer :weapon_hits_aa12
      t.integer :weapon_hits_peacemaker
      t.integer :weapon_hits_winchester1874
      t.integer :weapon_hits_plainsrider
      t.integer :weapon_hits_mateba
      t.integer :weapon_hits_asval
      t.integer :weapon_hits_sub2000
      t.integer :weapon_hits_hunter
      t.integer :weapon_hits_wa2000
      t.integer :weapon_hits_polymer
      t.integer :weapon_hits_arblast
      t.integer :weapon_hits_long
      t.integer :weapon_hits_frankish
      t.integer :weapon_hits_baka
      t.integer :weapon_used_par
      t.integer :weapon_used_model70
      t.integer :weapon_used_sparrow
      t.integer :melee_used_gator
      t.integer :melee_used_pugio
      t.integer :melee_used_selfie
      t.integer :melee_used_cutters
      t.integer :melee_used_boxcutter
      t.integer :melee_used_iceaxe
      t.integer :weapon_kills_par
      t.integer :weapon_kills_model70
      t.integer :weapon_kills_sparrow
      t.integer :melee_kills_gator
      t.integer :melee_kills_pugio
      t.integer :melee_kills_selfie
      t.integer :melee_kills_cutters
      t.integer :melee_kills_boxcutter
      t.integer :melee_kills_iceaxe
      t.integer :weapon_shots_par
      t.integer :weapon_shots_model70
      t.integer :weapon_shots_sparrow
      t.integer :weapon_hits_par
      t.integer :weapon_hits_model70
      t.integer :weapon_hits_sparrow
      t.integer :weapon_used_m37
      t.integer :melee_used_stick
      t.integer :melee_used_pitchfork
      t.integer :melee_used_scoutknife
      t.integer :melee_used_shawn
      t.integer :weapon_kills_m37
      t.integer :melee_kills_stick
      t.integer :melee_kills_pitchfork
      t.integer :melee_kills_scoutknife
      t.integer :melee_kills_shawn
      t.integer :weapon_shots_m37
      t.integer :weapon_hits_m37
      t.integer :weapon_used_china
      t.integer :melee_used_nin
      t.integer :weapon_kills_china
      t.integer :melee_kills_nin
      t.integer :weapon_shots_china
      t.integer :weapon_hits_china
      t.integer :weapon_used_sr2
      t.integer :weapon_used_x_sr2
      t.integer :melee_used_ballistic
      t.integer :weapon_kills_sr2
      t.integer :weapon_kills_x_sr2
      t.integer :melee_kills_ballistic
      t.integer :weapon_shots_sr2
      t.integer :weapon_shots_x_sr2
      t.integer :weapon_hits_sr2
      t.integer :weapon_hits_x_sr2
      t.integer :weapon_used_pl14
      t.integer :melee_used_zeus
      t.integer :weapon_kills_pl14
      t.integer :melee_kills_zeus
      t.integer :weapon_shots_pl14
      t.integer :weapon_hits_pl14
      t.integer :weapon_used_x_mp5
      t.integer :weapon_used_x_akmsu
      t.integer :weapon_kills_x_mp5
      t.integer :weapon_kills_x_akmsu
      t.integer :weapon_shots_x_mp5
      t.integer :weapon_shots_x_akmsu
      t.integer :weapon_hits_x_mp5
      t.integer :weapon_hits_x_akmsu
      t.integer :weapon_used_tecci
      t.integer :melee_used_wing
      t.integer :weapon_kills_tecci
      t.integer :melee_kills_wing
      t.integer :weapon_shots_tecci
      t.integer :weapon_hits_tecci
      t.integer :grenade_used_frag_com
      t.integer :grenade_kills_frag_com
      t.integer :weapon_used_hajk
      t.integer :weapon_used_boot
      t.integer :melee_used_road
      t.integer :grenade_used_wpn_prj_hur
      t.integer :weapon_kills_hajk
      t.integer :weapon_kills_boot
      t.integer :melee_kills_road
      t.integer :grenade_kills_wpn_prj_hur
      t.integer :weapon_shots_hajk
      t.integer :weapon_shots_boot
      t.integer :weapon_hits_hajk
      t.integer :weapon_hits_boot
      t.integer :weapon_used_rota
      t.integer :weapon_kills_rota
      t.integer :weapon_shots_rota
      t.integer :weapon_hits_rota
      t.integer :grenade_used_concussion
      t.integer :grenade_kills_concussion
      t.integer :grenade_used_wpn_prj_target
      t.integer :grenade_kills_wpn_prj_target
      t.integer :weapon_used_packrat
      t.integer :weapon_used_schakal
      t.integer :weapon_used_desertfox
      t.integer :weapon_used_x_packrat
      t.integer :weapon_kills_packrat
      t.integer :weapon_kills_schakal
      t.integer :weapon_kills_desertfox
      t.integer :weapon_kills_x_packrat
      t.integer :weapon_shots_packrat
      t.integer :weapon_shots_schakal
      t.integer :weapon_shots_desertfox
      t.integer :weapon_shots_x_packrat
      t.integer :weapon_hits_packrat
      t.integer :weapon_hits_schakal
      t.integer :weapon_hits_desertfox
      t.integer :weapon_hits_x_packrat
      t.integer :weapon_used_arbiter
      t.integer :weapon_kills_arbiter
      t.integer :weapon_shots_arbiter
      t.integer :weapon_hits_arbiter
      t.integer :melee_kills_brick
      t.integer :melee_kills_cs
      t.integer :melee_used_brick
      t.integer :melee_used_cs
      t.integer :weapon_hits_contraband
      t.integer :weapon_hits_ray
      t.integer :weapon_kills_contraband
      t.integer :weapon_kills_ray
      t.integer :weapon_shots_contraband
      t.integer :weapon_shots_ray
      t.integer :weapon_used_contraband
      t.integer :weapon_used_ray
      t.integer :melee_kills_ostry
      t.integer :melee_used_ostry
      t.integer :weapon_used_contraband_m203
      t.integer :weapon_shots_contraband_m203
      t.integer :weapon_kills_contraband_m203
      t.integer :weapon_used_tti
      t.integer :weapon_shots_tti
      t.integer :weapon_kills_tti
      t.integer :melee_kills_catch
      t.integer :melee_used_catch
      t.integer :weapon_hits_contraband_m203
      t.integer :weapon_hits_tti
      t.integer :weapon_used_siltstone
      t.integer :weapon_used_flint
      t.integer :weapon_used_coal
      t.integer :melee_used_oxide
      t.integer :weapon_kills_siltstone
      t.integer :weapon_kills_flint
      t.integer :weapon_kills_coal
      t.integer :melee_kills_oxide
      t.integer :weapon_shots_siltstone
      t.integer :weapon_shots_flint
      t.integer :weapon_hits_siltstone
      t.integer :weapon_hits_flint
      t.integer :weapon_hits_coal
      t.integer :weapon_shots_coal
      t.integer :weapon_used_lemming
      t.integer :grenade_used_fir_com
      t.integer :weapon_kills_lemming
      t.integer :grenade_kills_fir_com
      t.integer :weapon_shots_lemming
      t.integer :weapon_hits_lemming
      t.integer :melee_kills_sword
      t.integer :melee_used_sword
      t.integer :weapon_used_chinchilla
      t.integer :weapon_used_x_chinchilla
      t.integer :melee_used_agave
      t.integer :grenade_used_smoke_screen_grenade
      t.integer :weapon_kills_chinchilla
      t.integer :weapon_kills_x_chinchilla
      t.integer :melee_kills_agave
      t.integer :grenade_kills_smoke_screen_grenade
      t.integer :weapon_shots_chinchilla
      t.integer :weapon_shots_x_chinchilla
      t.integer :weapon_hits_chinchilla
      t.integer :weapon_hits_x_chinchilla
      t.integer :grenade_used_dada_com
      t.integer :grenade_kills_dada_com
      t.integer :weapon_shots_breech
      t.integer :weapon_hits_breech
      t.integer :weapon_shots_ching
      t.integer :weapon_hits_ching
      t.integer :weapon_kills_ching
      t.integer :weapon_hits_erma
      t.integer :weapon_kills_erma
      t.integer :weapon_used_breech
      t.integer :weapon_used_ching
      t.integer :weapon_used_erma
      t.integer :melee_used_push
      t.integer :melee_used_grip
      t.integer :melee_kills_push
      t.integer :melee_kills_grip
      t.integer :weapon_hits_basset
      t.integer :weapon_hits_shrew
      t.integer :weapon_used_x_shrew
      t.integer :melee_kills_sap
      t.integer :grenade_used_damage_control
      t.integer :weapon_used_basset
      t.integer :melee_used_sap
      t.integer :weapon_used_shrew
      t.integer :weapon_used_x_basset
      t.integer :weapon_kills_basset
      t.integer :weapon_kills_shrew
      t.integer :weapon_shots_x_shrew
      t.integer :weapon_hits_x_basset
      t.integer :weapon_hits_x_shrew
      t.integer :weapon_kills_breech
      t.integer :weapon_kills_x_basset
      t.integer :weapon_kills_x_shrew
      t.integer :grenade_kills_damage_control
      t.integer :weapon_shots_basset
      t.integer :weapon_shots_erma
      t.integer :weapon_shots_shrew
      t.integer :weapon_shots_x_basset
      t.integer :weapon_used_ecp
      t.integer :melee_used_meter
      t.integer :grenade_used_tag_team
      t.integer :weapon_kills_ecp
      t.integer :melee_kills_meter
      t.integer :grenade_kills_tag_team
      t.integer :weapon_shots_ecp
      t.integer :weapon_hits_ecp
      t.integer :melee_used_clean
      t.integer :weapon_used_corgi
      t.integer :melee_kills_clean
      t.integer :weapon_kills_corgi
      t.integer :weapon_shots_corgi
      t.integer :weapon_hits_corgi
      t.integer :weapon_used_slap
      t.integer :weapon_kills_slap
      t.integer :weapon_shots_slap
      t.integer :weapon_hits_slap
      t.integer :weapon_used_shuno
      t.integer :melee_used_aziz
      t.integer :melee_kills_aziz
      t.integer :weapon_kills_shuno
      t.integer :weapon_hits_shuno
      t.integer :weapon_shots_shuno
      t.integer :weapon_used_x_2006m
      t.integer :weapon_used_x_baka
      t.integer :weapon_used_x_breech
      t.integer :weapon_used_x_c96
      t.integer :weapon_used_x_coal
      t.integer :weapon_used_x_cobray
      t.integer :weapon_used_x_erma
      t.integer :weapon_used_x_g18c
      t.integer :weapon_used_x_hajk
      t.integer :weapon_used_x_hs2000
      t.integer :weapon_used_x_judge
      t.integer :weapon_used_x_m1928
      t.integer :weapon_used_x_m45
      t.integer :weapon_used_x_mac10
      t.integer :weapon_used_x_mp7
      t.integer :weapon_used_x_mp9
      t.integer :weapon_used_x_olympic
      t.integer :weapon_used_x_p226
      t.integer :weapon_used_x_p90
      t.integer :weapon_used_x_pl14
      t.integer :weapon_used_x_polymer
      t.integer :weapon_used_x_ppk
      t.integer :weapon_used_x_rage
      t.integer :weapon_used_x_rota
      t.integer :weapon_used_x_schakal
      t.integer :weapon_used_x_scorpion
      t.integer :weapon_used_x_sparrow
      t.integer :weapon_used_x_sterling
      t.integer :weapon_used_x_tec9
      t.integer :weapon_used_x_uzi
      t.integer :weapon_kills_x_2006m
      t.integer :weapon_kills_x_baka
      t.integer :weapon_kills_x_breech
      t.integer :weapon_kills_x_c96
      t.integer :weapon_kills_x_coal
      t.integer :weapon_kills_x_cobray
      t.integer :weapon_kills_x_erma
      t.integer :weapon_kills_x_g18c
      t.integer :weapon_kills_x_hajk
      t.integer :weapon_kills_x_hs2000
      t.integer :weapon_kills_x_judge
      t.integer :weapon_kills_x_m1928
      t.integer :weapon_kills_x_m45
      t.integer :weapon_kills_x_mac10
      t.integer :weapon_kills_x_mp7
      t.integer :weapon_kills_x_mp9
      t.integer :weapon_kills_x_olympic
      t.integer :weapon_kills_x_p226
      t.integer :weapon_kills_x_p90
      t.integer :weapon_kills_x_pl14
      t.integer :weapon_kills_x_polymer
      t.integer :weapon_kills_x_ppk
      t.integer :weapon_kills_x_rage
      t.integer :weapon_kills_x_rota
      t.integer :weapon_kills_x_schakal
      t.integer :weapon_kills_x_scorpion
      t.integer :weapon_kills_x_sparrow
      t.integer :weapon_kills_x_sterling
      t.integer :weapon_kills_x_tec9
      t.integer :weapon_kills_x_uzi
      t.integer :weapon_shots_x_2006m
      t.integer :weapon_shots_x_baka
      t.integer :weapon_shots_x_breech
      t.integer :weapon_shots_x_c96
      t.integer :weapon_shots_x_coal
      t.integer :weapon_shots_x_cobray
      t.integer :weapon_shots_x_erma
      t.integer :weapon_shots_x_g18c
      t.integer :weapon_shots_x_hajk
      t.integer :weapon_shots_x_hs2000
      t.integer :weapon_shots_x_judge
      t.integer :weapon_shots_x_m1928
      t.integer :weapon_shots_x_m45
      t.integer :weapon_shots_x_mac10
      t.integer :weapon_shots_x_mp7
      t.integer :weapon_shots_x_mp9
      t.integer :weapon_shots_x_olympic
      t.integer :weapon_shots_x_p226
      t.integer :weapon_shots_x_p90
      t.integer :weapon_shots_x_pl14
      t.integer :weapon_shots_x_polymer
      t.integer :weapon_shots_x_ppk
      t.integer :weapon_shots_x_rage
      t.integer :weapon_shots_x_rota
      t.integer :weapon_shots_x_schakal
      t.integer :weapon_shots_x_scorpion
      t.integer :weapon_shots_x_sparrow
      t.integer :weapon_shots_x_sterling
      t.integer :weapon_shots_x_tec9
      t.integer :weapon_shots_x_uzi
      t.integer :weapon_hits_x_2006m
      t.integer :weapon_hits_x_baka
      t.integer :weapon_hits_x_breech
      t.integer :weapon_hits_x_c96
      t.integer :weapon_hits_x_coal
      t.integer :weapon_hits_x_cobray
      t.integer :weapon_hits_x_erma
      t.integer :weapon_hits_x_g18c
      t.integer :weapon_hits_x_hajk
      t.integer :weapon_hits_x_hs2000
      t.integer :weapon_hits_x_judge
      t.integer :weapon_hits_x_m1928
      t.integer :weapon_hits_x_m45
      t.integer :weapon_hits_x_mac10
      t.integer :weapon_hits_x_mp7
      t.integer :weapon_hits_x_mp9
      t.integer :weapon_hits_x_olympic
      t.integer :weapon_hits_x_p226
      t.integer :weapon_hits_x_p90
      t.integer :weapon_hits_x_pl14
      t.integer :weapon_hits_x_polymer
      t.integer :weapon_hits_x_ppk
      t.integer :weapon_hits_x_rage
      t.integer :weapon_hits_x_rota
      t.integer :weapon_hits_x_schakal
      t.integer :weapon_hits_x_scorpion
      t.integer :weapon_hits_x_sparrow
      t.integer :weapon_hits_x_sterling
      t.integer :weapon_hits_x_tec9
      t.integer :weapon_hits_x_uzi
      t.integer :weapon_used_coach
      t.integer :weapon_used_elastic
      t.integer :weapon_used_komodo
      t.integer :weapon_used_legacy
      t.integer :weapon_used_shepheard
      t.integer :weapon_used_system
      t.integer :weapon_used_x_legacy
      t.integer :weapon_used_x_shepheard
      t.integer :melee_used_fear
      t.integer :melee_used_happy
      t.integer :melee_used_hauteur
      t.integer :melee_used_shock
      t.integer :weapon_kills_coach
      t.integer :weapon_kills_elastic
      t.integer :weapon_kills_komodo
      t.integer :weapon_kills_legacy
      t.integer :weapon_kills_shepheard
      t.integer :weapon_kills_system
      t.integer :weapon_kills_x_legacy
      t.integer :melee_kills_fear
      t.integer :melee_kills_happy
      t.integer :melee_kills_hauteur
      t.integer :melee_kills_shock
      t.integer :weapon_shots_coach
      t.integer :weapon_shots_elastic
      t.integer :weapon_shots_komodo
      t.integer :weapon_shots_legacy
      t.integer :weapon_shots_shepheard
      t.integer :weapon_shots_system
      t.integer :weapon_shots_x_shepheard
      t.integer :weapon_hits_coach
      t.integer :weapon_hits_elastic
      t.integer :weapon_hits_komodo
      t.integer :weapon_hits_legacy
      t.integer :weapon_hits_shepheard
      t.integer :weapon_hits_system
      t.integer :weapon_shots_x_legacy
      t.integer :weapon_hits_x_legacy
      t.integer :weapon_hits_x_shepheard
      t.integer :weapon_kills_x_shepheard
      t.integer :weapon_used_czech
      t.integer :weapon_used_stech
      t.integer :weapon_used_x_czech
      t.integer :melee_used_chac
      t.integer :weapon_kills_beer
      t.integer :weapon_kills_stech
      t.integer :weapon_kills_x_beer
      t.integer :weapon_kills_x_stech
      t.integer :weapon_shots_czech
      t.integer :weapon_shots_stech
      t.integer :weapon_shots_x_beer
      t.integer :weapon_shots_x_czech
      t.integer :weapon_shots_x_stech
      t.integer :weapon_hits_beer
      t.integer :weapon_hits_stech
      t.integer :weapon_hits_x_czech
      t.integer :weapon_color_used_color_tan_khaki
      t.integer :weapon_color_used_color_gray_black
      t.integer :weapon_color_used_color_green_money
      t.integer :weapon_color_used_color_blue_payday
      t.integer :weapon_color_used_color_green_dark
      t.integer :weapon_color_used_color_green_foliage
      t.integer :weapon_color_used_color_blue_gray
      t.integer :weapon_color_used_color_olive_brown
      t.integer :weapon_color_used_color_red
      t.integer :weapon_color_used_color_yellow
      t.integer :weapon_color_used_color_orange
      t.integer :weapon_color_used_color_mint
      t.integer :weapon_color_used_color_blue
      t.integer :weapon_color_used_color_purple
      t.integer :weapon_color_used_color_tan_chocolate
      t.integer :melee_kills_chac
      t.integer :weapon_used_beer
      t.integer :weapon_used_x_beer
      t.integer :weapon_used_x_stech
      t.integer :weapon_kills_czech
      t.integer :weapon_kills_x_czech
      t.integer :weapon_shots_beer
      t.integer :weapon_hits_czech
      t.integer :weapon_hits_x_beer
      t.integer :weapon_hits_x_stech
      t.integer :weapon_color_used_color_red_dark
      t.integer :weapon_color_used_color_green_gray
      t.integer :weapon_color_used_color_blue_bhodi
      t.integer :weapon_color_used_color_white
      t.integer :weapon_color_used_color_olive_green
      t.integer :weapon_color_used_color_tan
      t.integer :weapon_color_used_color_gray
      t.integer :weapon_color_used_color_green_intense
      t.integer :weapon_color_used_color_blue_navy
      t.integer :weapon_color_used_color_yellow_dark
      t.integer :weapon_color_used_color_pink
      t.integer :weapon_color_used_color_blue_ice
      t.integer :weapon_color_used_color_blue_teal
      t.integer :weapon_color_used_color_green_mellow
      t.integer :weapon_color_used_color_blue_deep
      t.integer :weapon_color_used_color_blue_deluxe
      t.integer :weapon_color_used_color_pink_cat
      t.integer :weapon_color_used_color_red_crust
      t.integer :weapon_color_used_color_camo_social_02
      t.integer :weapon_color_used_color_camo_04
      t.integer :weapon_color_used_color_camo_10
      t.integer :weapon_color_used_color_camo_14
      t.integer :weapon_color_used_color_camo_20
      t.integer :weapon_kills_m60
      t.integer :weapon_kills_r700
      t.integer :weapon_shots_m60
      t.integer :weapon_used_m60
      t.integer :weapon_used_r700
      t.integer :weapon_color_used_color_green_deluxe
      t.integer :weapon_color_used_color_purple_song
      t.integer :weapon_color_used_color_camo_free_02
      t.integer :weapon_color_used_color_camo_achievement_01
      t.integer :weapon_color_used_color_camo_01
      t.integer :weapon_color_used_color_camo_03
      t.integer :weapon_color_used_color_camo_05
      t.integer :weapon_color_used_color_camo_06
      t.integer :weapon_color_used_color_camo_07
      t.integer :weapon_color_used_color_camo_09
      t.integer :weapon_color_used_color_camo_11
      t.integer :weapon_color_used_color_camo_13
      t.integer :weapon_color_used_color_camo_16
      t.integer :weapon_color_used_color_camo_17
      t.integer :weapon_color_used_color_camo_18
      t.integer :weapon_color_used_color_immortal_python
      t.integer :weapon_kills_holt
      t.integer :weapon_kills_x_holt
      t.integer :weapon_shots_r700
      t.integer :weapon_hits_holt
      t.integer :weapon_hits_r700
      t.integer :weapon_hits_x_holt
      t.integer :weapon_used_holt
      t.integer :weapon_used_sbl
      t.integer :weapon_used_x_holt
      t.integer :weapon_used_x_model3
      t.integer :weapon_used_x_peacemaker
      t.integer :weapon_color_used_color_orange_mellow
      t.integer :weapon_color_used_color_camo_free_01
      t.integer :weapon_color_used_color_camo_social_01
      t.integer :weapon_color_used_color_camo_achievement_02
      t.integer :weapon_color_used_color_camo_02
      t.integer :weapon_color_used_color_camo_08
      t.integer :weapon_color_used_color_camo_12
      t.integer :weapon_color_used_color_camo_15
      t.integer :weapon_color_used_color_camo_19
      t.integer :weapon_color_used_color_anv_01
      t.integer :weapon_color_used_color_anv_02
      t.integer :weapon_color_used_color_anv_03
      t.integer :weapon_color_used_color_anv_04
      t.integer :weapon_color_used_color_anv_05
      t.integer :weapon_color_used_color_ocp_01
      t.integer :weapon_color_used_color_ocp_04
      t.integer :weapon_color_used_color_ocp_05
      t.integer :weapon_color_used_color_ocp_06
      t.integer :weapon_color_used_color_ocp_08
      t.integer :weapon_color_used_color_ocp_09
      t.integer :weapon_color_used_color_ocp_02
      t.integer :weapon_color_used_color_ocp_03
      t.integer :weapon_color_used_color_ocp_07
      t.integer :weapon_color_used_color_ocp_10
      t.integer :weapon_color_used_color_ocp_11
      t.integer :weapon_color_used_color_ocp_12
      t.integer :weapon_color_used_color_ocp_13
      t.integer :weapon_color_used_color_ocp_14
      t.integer :weapon_color_used_color_ocp_15
      t.integer :weapon_color_used_color_ocp_16
      t.integer :weapon_color_used_color_ocp_17
      t.integer :weapon_color_used_color_ocp_18
      t.integer :weapon_color_used_color_ocp_19
      t.integer :weapon_color_used_color_ocp_20
      t.integer :weapon_color_used_color_inf_01
      t.integer :weapon_color_used_color_inf_02
      t.integer :weapon_color_used_color_inf_03
      t.integer :weapon_color_used_color_inf_04
      t.integer :weapon_color_used_color_inf_05
      t.integer :weapon_color_used_color_inf_06
      t.integer :weapon_color_used_color_inf_07
      t.integer :weapon_color_used_color_inf_08
      t.integer :weapon_color_used_color_inf_09
      t.integer :weapon_color_used_color_inf_10
      t.integer :weapon_color_used_color_inf_11
      t.integer :weapon_color_used_color_inf_12
      t.integer :weapon_color_used_color_inf_13
      t.integer :weapon_color_used_color_inf_14
      t.integer :weapon_color_used_color_inf_15
      t.integer :weapon_color_used_color_inf_16
      t.integer :weapon_color_used_color_fex_01
      t.integer :weapon_color_used_color_fex_02
      t.integer :weapon_kills_m1897
      t.integer :weapon_kills_model3
      t.integer :weapon_kills_sbl
      t.integer :weapon_kills_x_lemming
      t.integer :weapon_kills_x_model3
      t.integer :weapon_kills_x_peacemaker
      t.integer :weapon_shots_holt
      t.integer :weapon_shots_m1897
      t.integer :weapon_shots_model3
      t.integer :weapon_shots_sbl
      t.integer :weapon_shots_x_holt
      t.integer :weapon_shots_x_lemming
      t.integer :weapon_shots_x_model3
      t.integer :weapon_shots_x_peacemaker
      t.integer :weapon_hits_m1897
      t.integer :weapon_hits_m60
      t.integer :weapon_hits_model3
      t.integer :weapon_hits_sbl
      t.integer :weapon_hits_x_lemming
      t.integer :weapon_hits_x_model3
      t.integer :weapon_hits_x_peacemaker
      t.integer :weapon_used_x_lemming
      t.integer :weapon_used_model3
      t.integer :weapon_used_m1897
      t.integer :weapon_used_m1911
      t.integer :weapon_used_m590
      t.integer :weapon_used_vityaz
      t.integer :weapon_used_x_vityaz
      t.integer :weapon_color_used_color_xm20_01
      t.integer :weapon_color_used_color_faco_02
      t.integer :weapon_color_used_color_faco_04
      t.integer :weapon_color_used_color_faco_05
      t.integer :weapon_color_used_color_faco_01
      t.integer :weapon_color_used_color_faco_03
      t.integer :weapon_color_used_color_faco_06
      t.integer :weapon_color_used_color_faco_08
      t.integer :weapon_color_used_color_faco_09
      t.integer :weapon_color_used_color_faco_10
      t.integer :weapon_color_used_color_faco_12
      t.integer :weapon_color_used_color_faco_13
      t.integer :weapon_color_used_color_faco_14
      t.integer :weapon_color_used_color_faco_15
      t.integer :weapon_color_used_color_faco_16
      t.integer :weapon_color_used_color_faco_17
      t.integer :weapon_color_used_color_faco_18
      t.integer :weapon_color_used_color_faco_19
      t.integer :weapon_color_used_color_faco_20
      t.integer :weapon_color_used_color_faco_00
      t.integer :weapon_color_used_color_in31_01
      t.integer :weapon_color_used_color_in31_02
      t.integer :weapon_color_used_color_in31_03
      t.integer :weapon_color_used_color_in31_04
      t.integer :weapon_color_used_color_in31_05
      t.integer :weapon_color_used_color_in31_06
      t.integer :weapon_color_used_color_in31_07
      t.integer :weapon_color_used_color_in31_08
      t.integer :weapon_kills_m590
      t.integer :weapon_kills_vityaz
      t.integer :weapon_kills_x_m1911
      t.integer :weapon_kills_x_vityaz
      t.integer :weapon_shots_m1911
      t.integer :weapon_shots_vityaz
      t.integer :weapon_shots_x_m1911
      t.integer :weapon_shots_x_vityaz
      t.integer :weapon_hits_m1911
      t.integer :weapon_hits_m590
      t.integer :weapon_hits_vityaz
      t.integer :weapon_hits_x_m1911
      t.integer :weapon_hits_x_vityaz
      t.integer :weapon_used_x_m1911
      t.integer :weapon_color_used_color_faco_07
      t.integer :weapon_color_used_color_faco_11
      t.integer :weapon_kills_m1911
      t.integer :weapon_shots_m590
      t.integer :weapon_color_used_color_mar21_01
      t.integer :melee_used_spoon
      t.integer :melee_used_spoon_gold
      t.integer :melee_kills_spoon
      t.integer :melee_kills_spoon_gold
      t.integer :weapon_color_used_color_in32_01
      t.integer :weapon_color_used_color_in32_02
      t.integer :weapon_color_used_color_in32_03
      t.integer :weapon_color_used_color_in32_04
      t.integer :weapon_color_used_color_in32_05
      t.integer :weapon_color_used_color_in32_06
      t.integer :weapon_color_used_color_in32_07
      t.integer :weapon_color_used_color_in32_08
      t.integer :weapon_color_used_color_in32_09
      t.integer :weapon_hits_x_pm9
      t.integer :weapon_hits_qbu88
      t.integer :weapon_hits_pm9
      t.integer :weapon_hits_groza_underbarrel
      t.integer :weapon_hits_groza
      t.integer :weapon_shots_x_pm9
      t.integer :weapon_shots_qbu88
      t.integer :weapon_shots_pm9
      t.integer :weapon_shots_groza_underbarrel
      t.integer :weapon_shots_groza
      t.integer :grenade_kills_wpn_gre_electric
      t.integer :weapon_kills_x_pm9
      t.integer :weapon_kills_qbu88
      t.integer :weapon_kills_pm9
      t.integer :weapon_kills_groza_underbarrel
      t.integer :weapon_kills_groza
      t.integer :weapon_color_used_color_sawp_10
      t.integer :weapon_color_used_color_sawp_09
      t.integer :weapon_color_used_color_sawp_08
      t.integer :weapon_color_used_color_sawp_07
      t.integer :weapon_color_used_color_sawp_06
      t.integer :weapon_color_used_color_sawp_05
      t.integer :weapon_color_used_color_sawp_04
      t.integer :weapon_color_used_color_sawp_03
      t.integer :weapon_color_used_color_sawp_02
      t.integer :weapon_color_used_color_sawp_01
      t.integer :grenade_used_wpn_gre_electric
      t.integer :weapon_used_x_pm9
      t.integer :weapon_used_qbu88
      t.integer :weapon_used_pm9
      t.integer :weapon_used_groza_underbarrel
      t.integer :weapon_used_groza
      t.integer :weapon_used_money
      t.integer :weapon_kills_money
      t.integer :weapon_shots_money
      t.integer :weapon_hits_money
      t.integer :weapon_used_rsh12
      t.integer :weapon_used_shak12
      t.integer :weapon_used_type54
      t.integer :weapon_used_type54_underbarrel
      t.integer :weapon_used_x_type54
      t.integer :weapon_used_x_type54_underbarrel
      t.integer :weapon_color_used_color_tawp_01
      t.integer :weapon_color_used_color_tawp_02
      t.integer :weapon_color_used_color_tawp_03
      t.integer :weapon_color_used_color_tawp_04
      t.integer :weapon_kills_shak12
      t.integer :weapon_kills_type54_underbarrel
      t.integer :weapon_kills_x_type54_underbarrel
      t.integer :weapon_shots_rsh12
      t.integer :weapon_shots_x_type54
      t.integer :weapon_hits_shak12
      t.integer :weapon_hits_type54_underbarrel
      t.integer :weapon_hits_x_type54_underbarrel
      t.integer :weapon_charm_used_wpn_fps_upg_charm_grenade
      t.integer :weapon_charm_used_wpn_fps_upg_charm_bag
      t.integer :weapon_charm_used_wpn_fps_upg_charm_piggy
      t.integer :weapon_charm_used_wpn_fps_upg_charm_dallas
      t.integer :weapon_charm_used_wpn_fps_upg_charm_cloaker
      t.integer :weapon_charm_used_wpn_fps_upg_charm_skulldozer
      t.integer :weapon_kills_rsh12
      t.integer :weapon_kills_type54
      t.integer :weapon_kills_x_type54
      t.integer :weapon_shots_shak12
      t.integer :weapon_shots_type54
      t.integer :weapon_shots_type54_underbarrel
      t.integer :weapon_shots_x_type54_underbarrel
      t.integer :weapon_hits_rsh12
      t.integer :weapon_hits_type54
      t.integer :weapon_hits_x_type54
      t.integer :weapon_charm_used_wpn_fps_upg_charm_pumpkin
      t.integer :weapon_color_used_color_in33_01
      t.integer :weapon_color_used_color_in33_02
      t.integer :weapon_color_used_color_in33_03
      t.integer :weapon_color_used_color_in33_04
      t.integer :weapon_color_used_color_in33_05
      t.integer :weapon_color_used_color_sbzac2_01
      t.integer :weapon_charm_used_wpn_fps_upg_charm_diamond
      t.integer :weapon_charm_used_wpn_fps_upg_charm_musket
      t.integer :weapon_charm_used_wpn_fps_upg_charm_pyramid
      t.integer :weapon_charm_used_wpn_fps_upg_charm_skullz
      t.integer :weapon_charm_used_wpn_fps_upg_charm_toast
      t.integer :weapon_color_used_color_snow_01
      t.integer :weapon_color_used_color_snow_02
      t.integer :weapon_color_used_color_snow_03
      t.integer :weapon_color_used_color_snow_04
      t.integer :grenade_used_xmas_snowball
      t.integer :grenade_kills_xmas_snowball
      t.integer :weapon_charm_used_wpn_fps_upg_charm_ball
      t.integer :weapon_charm_used_wpn_fps_upg_charm_choco
      t.integer :weapon_charm_used_wpn_fps_upg_charm_flake
      t.integer :weapon_charm_used_wpn_fps_upg_charm_igloo
      t.integer :weapon_charm_used_wpn_fps_upg_charm_lusse
      t.integer :weapon_charm_used_wpn_fps_upg_charm_snow
      t.integer :weapon_charm_used_wpn_fps_upg_charm_tiger
      t.integer :weapon_used_fmg9
      t.integer :weapon_used_maxim9
      t.integer :weapon_used_ultima
      t.integer :weapon_used_x_maxim9
      t.integer :weapon_color_used_color_lawp_01
      t.integer :weapon_color_used_color_lawp_02
      t.integer :weapon_color_used_color_lawp_03
      t.integer :weapon_color_used_color_lawp_04
      t.integer :weapon_kills_fmg9
      t.integer :weapon_kills_maxim9
      t.integer :weapon_kills_ultima
      t.integer :weapon_kills_x_maxim9
      t.integer :weapon_shots_fmg9
      t.integer :weapon_shots_maxim9
      t.integer :weapon_shots_ultima
      t.integer :weapon_shots_x_maxim9
      t.integer :weapon_hits_fmg9
      t.integer :weapon_hits_maxim9
      t.integer :weapon_hits_ultima
      t.integer :weapon_hits_x_maxim9
      t.integer :weapon_used_hk51b
      t.integer :weapon_used_ms3gl
      t.integer :weapon_used_scout
      t.integer :grenade_used_poison_gas_grenade
      t.integer :weapon_charm_used_wpn_fps_upg_charm_cactus
      t.integer :weapon_charm_used_wpn_fps_upg_charm_cowboy_hat
      t.integer :weapon_charm_used_wpn_fps_upg_charm_horseshoe
      t.integer :weapon_charm_used_wpn_fps_upg_charm_nascar
      t.integer :weapon_charm_used_wpn_fps_upg_charm_pokerchip
      t.integer :weapon_charm_used_wpn_fps_upg_charm_rangerbadge
      t.integer :weapon_kills_hk51b
      t.integer :weapon_kills_ms3gl
      t.integer :weapon_kills_scout
      t.integer :grenade_kills_poison_gas_grenade
      t.integer :weapon_shots_hk51b
      t.integer :weapon_shots_ms3gl
      t.integer :weapon_shots_scout
      t.integer :weapon_hits_hk51b
      t.integer :weapon_hits_ms3gl
      t.integer :weapon_hits_scout
      t.integer :weapon_used_ranc_heavy_machine_gun
      t.integer :weapon_kills_ranc_heavy_machine_gun
      t.integer :weapon_shots_ranc_heavy_machine_gun
      t.integer :weapon_hits_ranc_heavy_machine_gun
      t.integer :weapon_charm_used_wpn_fps_upg_charm_piggy_gold
      t.integer :weapon_charm_used_wpn_fps_upg_charm_rooster
      t.integer :weapon_color_used_color_tma1_01
      t.integer :weapon_hits_x_sko12
      t.integer :weapon_hits_sko12
      t.integer :weapon_shots_x_sko12
      t.integer :weapon_shots_sko12
      t.integer :weapon_kills_x_sko12
      t.integer :weapon_kills_sko12
      t.integer :weapon_used_sko12
      t.integer :weapon_used_x_sko12
      t.integer :weapon_charm_used_wpn_fps_upg_charm_beer
      t.integer :weapon_charm_used_wpn_fps_upg_charm_foam
      t.integer :weapon_charm_used_wpn_fps_upg_charm_skull
      t.integer :weapon_used_hailstorm
      t.integer :weapon_kills_hailstorm
      t.integer :weapon_shots_hailstorm
      t.integer :weapon_hits_hailstorm
      t.integer :weapon_used_korth
      t.integer :weapon_used_x_korth
      t.integer :weapon_kills_korth
      t.integer :weapon_kills_x_korth
      t.integer :weapon_shots_korth
      t.integer :weapon_shots_x_korth
      t.integer :weapon_hits_korth
      t.integer :weapon_hits_x_korth
      t.integer :weapon_used_victor
      t.integer :weapon_kills_victor
      t.integer :weapon_shots_victor
      t.integer :weapon_hits_victor
      t.integer :grenade_used_sticky_grenade
      t.integer :grenade_kills_sticky_grenade
      t.integer :weapon_charm_used_wpn_fps_upg_charm_teddymoo
      t.integer :weapon_used_contender
      t.integer :weapon_used_hcar
      t.integer :weapon_used_tkb
      t.integer :weapon_kills_contender
      t.integer :weapon_kills_hcar
      t.integer :weapon_kills_tkb
      t.integer :weapon_shots_contender
      t.integer :weapon_shots_hcar
      t.integer :weapon_shots_tkb
      t.integer :weapon_hits_contender
      t.integer :weapon_hits_hcar
      t.integer :weapon_hits_tkb
      t.timestamps
    end
  end
end
