class CreateMiscStats < ActiveRecord::Migration[7.0]
  def change
    create_table :misc_stats do |t|
      t.belongs_to :user
      t.integer :heist_dropin
      t.integer :heist_failed
      t.integer :heist_success
      t.integer :gadget_used_ammo_bag
      t.integer :gadget_used_doctor_bag
      t.integer :gadget_used_trip_mine
      t.integer :gadget_used_sentry_gun
      t.integer :gadget_used_ecm_jammer
      t.integer :difficulty_easy
      t.integer :difficulty_normal
      t.integer :difficulty_hard
      t.integer :difficulty_overkill
      t.integer :difficulty_overkill_145
      t.integer :halloween_4_stats
      t.integer :halloween_5_stats
      t.integer :halloween_6_stats
      t.integer :halloween_7_stats
      t.integer :halloween_8_stats
      t.integer :halloween_10_stats
      t.integer :armored_4_stat
      t.integer :armored_5_stat
      t.integer :armored_7_stat
      t.integer :armored_8_stat
      t.integer :armored_9_stat
      t.integer :armored_10_stat
      t.integer :level_safehouse
      t.integer :level_jewelry_store
      t.integer :level_four_stores
      t.integer :level_nightclub
      t.integer :level_mallcrasher
      t.integer :level_ukrainian_job
      t.integer :level_framing_frame_1
      t.integer :level_framing_frame_2
      t.integer :level_framing_frame_3
      t.integer :level_alex_1
      t.integer :level_alex_2
      t.integer :level_alex_3
      t.integer :level_watchdogs_1
      t.integer :level_watchdogs_2
      t.integer :level_firestarter_1
      t.integer :level_firestarter_2
      t.integer :level_firestarter_3
      t.integer :level_welcome_to_the_jungle_1
      t.integer :level_welcome_to_the_jungle_2
      t.integer :level_escape_cafe_day
      t.integer :level_escape_park_day
      t.integer :level_escape_cafe
      t.integer :level_escape_park
      t.integer :level_escape_street
      t.integer :level_escape_overpass
      t.integer :level_escape_garage
      t.integer :level_family
      t.integer :level_arm_cro
      t.integer :level_arm_und
      t.integer :level_arm_hcm
      t.integer :level_arm_par
      t.integer :level_arm_fac
      t.integer :level_arm_for
      t.integer :level_branchbank
      t.integer :job_four_stores
      t.integer :job_nightclub
      t.integer :job_mallcrasher
      t.integer :job_ukrainian_job_prof
      t.integer :job_branchbank_deposit
      t.integer :job_branchbank_cash
      t.integer :job_branchbank_gold_prof
      t.integer :job_branchbank_prof
      t.integer :job_framing_frame
      t.integer :job_framing_frame_prof
      t.integer :job_alex
      t.integer :job_alex_prof
      t.integer :job_watchdogs
      t.integer :job_watchdogs_prof
      t.integer :job_firestarter
      t.integer :job_firestarter_prof
      t.integer :job_welcome_to_the_jungle_prof
      t.integer :job_family
      t.integer :job_arm_fac
      t.integer :job_arm_par
      t.integer :job_arm_hcm
      t.integer :job_arm_und
      t.integer :job_arm_cro
      t.integer :job_jewelry_store
      t.integer :payday2
      t.integer :gage_1_stats
      t.integer :gage_2_stats
      t.integer :gage_3_stats
      t.integer :gage_4_stats
      t.integer :gage_5_stats
      t.integer :gage_6_stats
      t.integer :gage_9_stats
      t.integer :gage_10_stats
      t.integer :gage_7_stats
      t.integer :gage2_3_stats
      t.integer :gage2_9_stats
      t.integer :stats_election_day_s
      t.integer :stats_election_day_n
      t.integer :level_election_day_1
      t.integer :level_election_day_2
      t.integer :level_election_day_3_skip1
      t.integer :level_election_day_3_skip2
      t.integer :level_roberts
      t.integer :job_election_day
      t.integer :job_election_day_prof
      t.integer :job_roberts
      t.integer :difficulty_overkill_290
      t.integer :gmod_1_stats
      t.integer :gmod_2_stats
      t.integer :gmod_3_stats
      t.integer :gmod_4_stats
      t.integer :gmod_5_stats
      t.integer :gage3_2_stats
      t.integer :gage3_3_stats
      t.integer :gage3_4_stats
      t.integer :gage3_5_stats
      t.integer :gage3_6_stats
      t.integer :gage3_7_stats
      t.integer :gage3_10_stats
      t.integer :gage3_11_stats
      t.integer :gage3_13_stats
      t.integer :gage3_14_stats
      t.integer :gage3_15_stats
      t.integer :gage3_16_stats
      t.integer :gage3_17_stats
      t.integer :gage3_12_stats
      t.integer :level_kosugi
      t.integer :level_big
      t.integer :job_kosugi
      t.integer :job_big
      t.integer :gage4_6_stats
      t.integer :gage4_7_stats
      t.integer :gage4_8_stats
      t.integer :gage4_10_stats
      t.integer :armor_used_level_1
      t.integer :armor_used_level_2
      t.integer :armor_used_level_3
      t.integer :armor_used_level_4
      t.integer :armor_used_level_5
      t.integer :armor_used_level_6
      t.integer :armor_used_level_7
      t.integer :enemy_kills_cop
      t.integer :enemy_kills_fbi
      t.integer :enemy_kills_fbi_swat
      t.integer :enemy_kills_fbi_heavy_swat
      t.integer :enemy_kills_swat
      t.integer :enemy_kills_heavy_swat
      t.integer :enemy_kills_city_swat
      t.integer :enemy_kills_security
      t.integer :enemy_kills_gensec
      t.integer :enemy_kills_gangster
      t.integer :enemy_kills_biker_escape
      t.integer :enemy_kills_sniper
      t.integer :enemy_kills_shield
      t.integer :enemy_kills_spooc
      t.integer :enemy_kills_tank
      t.integer :enemy_kills_taser
      t.integer :contract_jewelry_store_win
      t.integer :contract_jewelry_store_win_dropin
      t.integer :contract_jewelry_store_fail
      t.integer :contract_four_stores_win
      t.integer :contract_four_stores_win_dropin
      t.integer :contract_four_stores_fail
      t.integer :contract_nightclub_win
      t.integer :contract_nightclub_win_dropin
      t.integer :contract_nightclub_fail
      t.integer :contract_mallcrasher_win
      t.integer :contract_mallcrasher_win_dropin
      t.integer :contract_mallcrasher_fail
      t.integer :contract_ukrainian_job_prof_win
      t.integer :contract_ukrainian_job_prof_win_dropin
      t.integer :contract_ukrainian_job_prof_fail
      t.integer :contract_branchbank_deposit_win
      t.integer :contract_branchbank_deposit_win_dropin
      t.integer :contract_branchbank_deposit_fail
      t.integer :contract_branchbank_cash_win
      t.integer :contract_branchbank_cash_win_dropin
      t.integer :contract_branchbank_cash_fail
      t.integer :contract_branchbank_gold_prof_win
      t.integer :contract_branchbank_gold_prof_win_dropin
      t.integer :contract_branchbank_gold_prof_fail
      t.integer :contract_branchbank_prof_win
      t.integer :contract_branchbank_prof_win_dropin
      t.integer :contract_branchbank_prof_fail
      t.integer :contract_framing_frame_win
      t.integer :contract_framing_frame_win_dropin
      t.integer :contract_framing_frame_fail
      t.integer :contract_framing_frame_prof_win
      t.integer :contract_framing_frame_prof_win_dropin
      t.integer :contract_framing_frame_prof_fail
      t.integer :contract_alex_win
      t.integer :contract_alex_win_dropin
      t.integer :contract_alex_fail
      t.integer :contract_alex_prof_win
      t.integer :contract_alex_prof_win_dropin
      t.integer :contract_alex_prof_fail
      t.integer :contract_watchdogs_win
      t.integer :contract_watchdogs_win_dropin
      t.integer :contract_watchdogs_fail
      t.integer :contract_watchdogs_prof_win
      t.integer :contract_watchdogs_prof_win_dropin
      t.integer :contract_watchdogs_prof_fail
      t.integer :contract_firestarter_win
      t.integer :contract_firestarter_win_dropin
      t.integer :contract_firestarter_fail
      t.integer :contract_firestarter_prof_win
      t.integer :contract_firestarter_prof_win_dropin
      t.integer :contract_firestarter_prof_fail
      t.integer :contract_welcome_to_the_jungle_prof_win
      t.integer :contract_welcome_to_the_jungle_prof_win_dropin
      t.integer :contract_welcome_to_the_jungle_prof_fail
      t.integer :contract_family_win
      t.integer :contract_family_win_dropin
      t.integer :contract_family_fail
      t.integer :contract_arm_fac_win
      t.integer :contract_arm_fac_win_dropin
      t.integer :contract_arm_fac_fail
      t.integer :contract_arm_par_win
      t.integer :contract_arm_par_win_dropin
      t.integer :contract_arm_par_fail
      t.integer :contract_arm_hcm_win
      t.integer :contract_arm_hcm_win_dropin
      t.integer :contract_arm_hcm_fail
      t.integer :contract_arm_und_win
      t.integer :contract_arm_und_win_dropin
      t.integer :contract_arm_und_fail
      t.integer :contract_arm_cro_win
      t.integer :contract_arm_cro_win_dropin
      t.integer :contract_arm_cro_fail
      t.integer :contract_roberts_win
      t.integer :contract_roberts_win_dropin
      t.integer :contract_roberts_fail
      t.integer :contract_election_day_win
      t.integer :contract_election_day_win_dropin
      t.integer :contract_election_day_fail
      t.integer :contract_election_day_prof_win
      t.integer :contract_election_day_prof_win_dropin
      t.integer :contract_election_day_prof_fail
      t.integer :contract_kosugi_win
      t.integer :contract_kosugi_win_dropin
      t.integer :contract_kosugi_fail
      t.integer :contract_big_win
      t.integer :contract_big_win_dropin
      t.integer :contract_big_fail
      t.integer :stat_version
      t.integer :gage5_1_stats
      t.integer :gage5_5_stats
      t.integer :gage5_8_stats
      t.integer :gage5_9_stats
      t.integer :gage5_10_stats
      t.integer :pig_3_stats
      t.integer :enemy_kills_mobster
      t.integer :enemy_kills_mobster_boss
      t.integer :level_mia_1
      t.integer :level_mia_2
      t.integer :job_mia
      t.integer :job_mia_prof
      t.integer :contract_mia_win
      t.integer :contract_mia_win_dropin
      t.integer :contract_mia_fail
      t.integer :contract_mia_prof_win
      t.integer :contract_mia_prof_win_dropin
      t.integer :contract_mia_prof_fail
      t.integer :character_used_russian
      t.integer :character_used_german
      t.integer :character_used_spanish
      t.integer :character_used_american
      t.integer :character_used_jowi
      t.integer :character_used_old_hoxton
      t.integer :level_watchdogs_1_night
      t.integer :level_watchdogs_2_day
      t.integer :level_welcome_to_the_jungle_1_night
      t.integer :level_gallery
      t.integer :job_gallery
      t.integer :contract_gallery_win
      t.integer :contract_gallery_win_dropin
      t.integer :contract_gallery_fail
      t.integer :level_hox_1
      t.integer :level_hox_2
      t.integer :job_hox
      t.integer :job_hox_prof
      t.integer :contract_hox_win
      t.integer :contract_hox_win_dropin
      t.integer :contract_hox_fail
      t.integer :contract_hox_prof_win
      t.integer :contract_hox_prof_win_dropin
      t.integer :contract_hox_prof_fail
      t.integer :enemy_kills_civilian
      t.integer :enemy_kills_civilian_female
      t.integer :level_haunted
      t.integer :job_haunted
      t.integer :contract_haunted_win
      t.integer :contract_haunted_win_dropin
      t.integer :contract_haunted_fail
      t.integer :enemy_kills_tank_hw
      t.integer :eagle_1_stats
      t.integer :eagle_2_stats
      t.integer :character_used_female_1
      t.integer :gadget_used_first_aid
      t.integer :gadget_used_body_bag
      t.integer :gadget_used_armor_bag
      t.integer :option_decide_host
      t.integer :option_decide_vote
      t.integer :option_decide_none
      t.integer :contract_fail
      t.integer :contract_win
      t.integer :info_playing_win_host
      t.integer :info_playing_win_client
      t.integer :info_playing_win_client_dropin
      t.integer :info_playing_fail_host
      t.integer :info_playing_fail_client
      t.integer :info_playing_normal
      t.integer :info_playing_beta
      t.integer :level_pines
      t.integer :job_pines
      t.integer :contract_pines_win
      t.integer :contract_pines_win_dropin
      t.integer :contract_pines_fail
      t.integer :level_mus
      t.integer :job_mus
      t.integer :contract_mus_win
      t.integer :contract_mus_win_dropin
      t.integer :contract_mus_fail
      t.integer :contract_watchdogs_night_win
      t.integer :contract_watchdogs_night_win_dropin
      t.integer :contract_watchdogs_night_fail
      t.integer :contract_watchdogs_night_prof_win
      t.integer :contract_watchdogs_night_prof_win_dropin
      t.integer :contract_watchdogs_night_prof_fail
      t.integer :contract_welcome_to_the_jungle_night_prof_win
      t.integer :contract_welcome_to_the_jungle_night_prof_win_dropin
      t.integer :contract_welcome_to_the_jungle_night_prof_fail
      t.integer :job_watchdogs_night
      t.integer :job_watchdogs_night_prof
      t.integer :job_welcome_to_the_jungle_night_prof
      t.integer :character_used_dragan
      t.integer :level_crojob2
      t.integer :level_crojob3
      t.integer :job_crojob1
      t.integer :job_crojob2
      t.integer :contract_crojob1_win
      t.integer :contract_crojob1_win_dropin
      t.integer :contract_crojob1_fail
      t.integer :contract_crojob2_win
      t.integer :contract_crojob2_win_dropin
      t.integer :contract_crojob2_fail
      t.integer :ameno_08_stats
      t.integer :level_crojob3_night
      t.integer :job_crojob2_night
      t.integer :contract_crojob2_night_win
      t.integer :contract_crojob2_night_win_dropin
      t.integer :contract_crojob2_night_fail
      t.integer :character_used_jacket
      t.integer :character_used_bonnie
      t.integer :level_rat
      t.integer :job_rat
      t.integer :job_arm_for
      t.integer :contract_rat_win
      t.integer :contract_rat_win_dropin
      t.integer :contract_rat_fail
      t.integer :contract_arm_for_win
      t.integer :contract_arm_for_win_dropin
      t.integer :contract_arm_for_fail
      t.integer :level_cage
      t.integer :job_cage
      t.integer :contract_cage_win
      t.integer :contract_cage_win_dropin
      t.integer :contract_cage_fail
      t.integer :specialization_used_0
      t.integer :specialization_used_1
      t.integer :specialization_used_2
      t.integer :specialization_used_3
      t.integer :specialization_used_4
      t.integer :specialization_used_5
      t.integer :specialization_used_6
      t.integer :specialization_used_7
      t.integer :specialization_used_8
      t.integer :specialization_used_9
      t.integer :specialization_used_10
      t.integer :level_hox_3
      t.integer :job_hox_3
      t.integer :contract_hox_3_win
      t.integer :contract_hox_3_win_dropin
      t.integer :contract_hox_3_fail
      t.integer :enemy_kills_hector_boss
      t.integer :enemy_kills_hector_boss_no_armor
      t.integer :scorpion_1_stats
      t.integer :level_shoutout_raid
      t.integer :job_shoutout_raid
      t.integer :contract_shoutout_raid_win
      t.integer :contract_shoutout_raid_win_dropin
      t.integer :contract_shoutout_raid_fail
      t.integer :character_used_sokol
      t.integer :level_arena
      t.integer :level_kenaz
      t.integer :job_arena
      t.integer :job_kenaz
      t.integer :contract_arena_win
      t.integer :contract_arena_win_dropin
      t.integer :contract_arena_fail
      t.integer :contract_kenaz_win
      t.integer :contract_kenaz_win_dropin
      t.integer :contract_kenaz_fail
      t.integer :specialization_used_11
      t.integer :specialization_used_12
      t.integer :character_used_dragon
      t.integer :option_resolution_2560x1440
      t.integer :option_resolution_1920x1200
      t.integer :option_resolution_1920x1080
      t.integer :option_resolution_1680x1050
      t.integer :option_resolution_1600x900
      t.integer :option_resolution_1536x864
      t.integer :option_resolution_1440x900
      t.integer :option_resolution_1366x768
      t.integer :option_resolution_1360x768
      t.integer :option_resolution_1280x1024
      t.integer :option_resolution_1280x800
      t.integer :option_resolution_1280x720
      t.integer :option_resolution_1024x768
      t.integer :option_resolution_other
      t.integer :equipped_mask
      t.integer :equipped_primary
      t.integer :equipped_secondary
      t.integer :equipped_melee
      t.integer :equipped_grenade
      t.integer :equipped_armor
      t.integer :equipped_character
      t.integer :equipped_deployable
      t.integer :enemy_kills_tank_green
      t.integer :enemy_kills_tank_black
      t.integer :enemy_kills_tank_skull
      t.integer :enemy_kills_hostage_rescue
      t.integer :enemy_kills_murkywater
      t.integer :enemy_kills_phalanx_vip
      t.integer :enemy_kills_phalanx_minion
      t.integer :crimefest_challenge_dallas_1
      t.integer :crimefest_challenge_chains_1
      t.integer :crimefest_challenge_clover_1
      t.integer :crimefest_challenge_houston_2
      t.integer :crimefest_challenge_clover_2
      t.integer :crimefest_challenge_houston_1
      t.integer :crimefest_challenge_dallas_2
      t.integer :crimefest_challenge_chains_2
      t.integer :crimefest_challenge_dallas_3
      t.integer :crimefest_challenge_chains_3
      t.integer :crimefest_challenge_houston_3
      t.integer :crimefest_challenge_clover_3
      t.integer :crimefest_challenge_chains_4
      t.integer :crimefest_challenge_houston_4
      t.integer :crimefest_challenge_clover_4
      t.integer :crimefest_challenge_dallas_5
      t.integer :crimefest_challenge_chains_5
      t.integer :crimefest_challenge_houston_5
      t.integer :crimefest_challenge_clover_5
      t.integer :crimefest_challenge_dallas_6
      t.integer :crimefest_challenge_chains_6
      t.integer :crimefest_challenge_clover_6
      t.integer :crimefest_challenge_final
      t.integer :mission_labrat
      t.integer :specialization_used_13
      t.integer :level_jolly
      t.integer :level_red2
      t.integer :level_dinner
      t.integer :level_nail
      t.integer :level_pbr
      t.integer :level_pbr2
      t.integer :job_jolly
      t.integer :job_nail
      t.integer :job_red2
      t.integer :job_dinner
      t.integer :job_pbr
      t.integer :job_pbr2
      t.integer :contract_jolly_win
      t.integer :contract_jolly_win_dropin
      t.integer :contract_jolly_fail
      t.integer :contract_nail_win
      t.integer :contract_nail_win_dropin
      t.integer :contract_nail_fail
      t.integer :contract_red2_win
      t.integer :contract_red2_win_dropin
      t.integer :contract_red2_fail
      t.integer :contract_dinner_win
      t.integer :contract_dinner_win_dropin
      t.integer :contract_dinner_fail
      t.integer :contract_pbr_win
      t.integer :contract_pbr_win_dropin
      t.integer :contract_pbr_fail
      t.integer :contract_pbr2_win
      t.integer :contract_pbr2_win_dropin
      t.integer :contract_pbr2_fail
      t.integer :character_used_bodhi
      t.integer :enemy_kills_biker
      t.integer :enemy_kills_inside_man
      t.integer :enemy_kills_bank_manager
      t.integer :level_cane
      t.integer :level_peta
      t.integer :level_peta2
      t.integer :job_cane
      t.integer :job_peta
      t.integer :job_peta_prof
      t.integer :contract_cane_win
      t.integer :contract_cane_win_dropin
      t.integer :contract_cane_fail
      t.integer :contract_peta_win
      t.integer :contract_peta_win_dropin
      t.integer :contract_peta_fail
      t.integer :contract_peta_prof_win
      t.integer :contract_peta_prof_win_dropin
      t.integer :contract_peta_prof_fail
      t.integer :level_pal
      t.integer :level_man
      t.integer :job_pal
      t.integer :job_man
      t.integer :contract_pal_win
      t.integer :contract_pal_win_dropin
      t.integer :contract_pal_fail
      t.integer :contract_man_win
      t.integer :contract_man_win_dropin
      t.integer :contract_man_fail
      t.integer :specialization_used_14
      t.integer :character_used_jimmy
      t.integer :level_dark
      t.integer :level_mad
      t.integer :job_dark
      t.integer :job_mad
      t.integer :contract_dark_win
      t.integer :contract_dark_win_dropin
      t.integer :contract_dark_fail
      t.integer :contract_mad_win
      t.integer :contract_mad_win_dropin
      t.integer :contract_mad_fail
      t.integer :info_playing_pc_beta
      t.integer :info_playing_linux_beta
      t.integer :specialization_used_15
      t.integer :character_used_sydney
      t.integer :info_playing_pc
      t.integer :info_playing_linux
      t.integer :enemy_kills_cop_scared
      t.integer :info_playing_tutorial_yes
      t.integer :info_playing_tutorial_no
      t.integer :specialization_used_16
      t.integer :level_born
      t.integer :level_chew
      t.integer :job_born
      t.integer :job_born_pro
      t.integer :contract_born_win
      t.integer :contract_born_win_dropin
      t.integer :contract_born_fail
      t.integer :contract_born_pro_win
      t.integer :contract_born_pro_win_dropin
      t.integer :contract_born_pro_fail
      t.integer :character_used_wild
      t.integer :enemy_kills_biker_boss
      t.integer :enemy_kills_cop_female
      t.integer :difficulty_easy_wish
      t.integer :difficulty_sm_wish
      t.integer :level_chill
      t.integer :level_chill_combat
      t.integer :level_flat
      t.integer :job_chill
      t.integer :job_chill_combat
      t.integer :job_flat
      t.integer :contract_chill_win
      t.integer :contract_chill_win_dropin
      t.integer :contract_chill_fail
      t.integer :contract_chill_pro_win
      t.integer :contract_chill_pro_win_dropin
      t.integer :contract_chill_pro_fail
      t.integer :contract_chill_combat_win
      t.integer :contract_chill_combat_win_dropin
      t.integer :contract_chill_combat_fail
      t.integer :contract_chill_combat_pro_win
      t.integer :contract_chill_combat_pro_win_dropin
      t.integer :contract_chill_combat_pro_fail
      t.integer :contract_flat_win
      t.integer :contract_flat_win_dropin
      t.integer :contract_flat_fail
      t.integer :contract_flat_pro_win
      t.integer :contract_flat_pro_win_dropin
      t.integer :contract_flat_pro_fail
      t.integer :enemy_kills_medic
      t.integer :enemy_kills_robbers_safehouse
      t.integer :enemy_kills_chavez_boss
      t.integer :enemy_kills_security_undominatable
      t.integer :pim_1_stats
      t.integer :pim_3_stats
      t.integer :pim_2_stats
      t.integer :level_help
      t.integer :job_help
      t.integer :contract_help_win
      t.integer :contract_help_win_dropin
      t.integer :contract_help_fail
      t.integer :tango_2_stats
      t.integer :level_moon
      t.integer :job_moon
      t.integer :contract_moon_win
      t.integer :contract_moon_win_dropin
      t.integer :contract_moon_fail
      t.integer :character_used_chico
      t.integer :contract_friend_fail
      t.integer :contract_friend_win
      t.integer :contract_friend_win_dropin
      t.integer :enemy_kills_bolivian
      t.integer :enemy_kills_bolivian_indoors
      t.integer :enemy_kills_drug_lord_boss
      t.integer :enemy_kills_drug_lord_boss_stealth
      t.integer :job_friend
      t.integer :level_friend
      t.integer :job_spa
      t.integer :level_spa
      t.integer :job_fish
      t.integer :level_fish
      t.integer :contract_spa_win
      t.integer :contract_spa_win_dropin
      t.integer :contract_spa_fail
      t.integer :contract_fish_win
      t.integer :contract_fish_fail
      t.integer :grv_3_stats
      t.integer :contract_fish_win_dropin
      t.integer :type_kills_gangster
      t.integer :type_kills_civilians
      t.integer :sb17_challenge_1
      t.integer :sb17_challenge_2
      t.integer :sb17_challenge_4
      t.integer :sb17_challenge_5
      t.integer :sb17_challenge_6
      t.integer :sb17_challenge_7
      t.integer :type_kills_law
      t.integer :level_run
      t.integer :job_run
      t.integer :contract_run_win
      t.integer :contract_run_win_dropin
      t.integer :contract_run_fail
      t.integer :enemy_kills_escort_chinese_prisoner
      t.integer :contract_glace_win
      t.integer :contract_glace_win_dropin
      t.integer :contract_glace_fail
      t.integer :sb17_challenge_8
      t.integer :specialization_used_17
      t.integer :specialization_used_18
      t.integer :level_glace
      t.integer :job_glace
      t.integer :character_used_max
      t.integer :eng_1_stats
      t.integer :eng_3_stats
      t.integer :eng_4_stats
      t.integer :eng_2_stats
      t.integer :contract_hvh_fail
      t.integer :contract_dah_fail
      t.integer :contract_wwh_fail
      t.integer :contract_dah_win_dropin
      t.integer :contract_hvh_win_dropin
      t.integer :contract_wwh_win_dropin
      t.integer :contract_hvh_win
      t.integer :contract_dah_win
      t.integer :contract_wwh_win
      t.integer :job_hvh
      t.integer :job_dah
      t.integer :job_wwh
      t.integer :level_election_day_3
      t.integer :level_dah
      t.integer :level_escape_overpass_night
      t.integer :level_hvh
      t.integer :level_wwh
      t.integer :character_used_myh
      t.integer :specialization_used_19
      t.integer :specialization_used_20
      t.integer :character_used_ecp_male
      t.integer :character_used_ecp_female
      t.integer :rvd_12_stats
      t.integer :contract_rvd_fail
      t.integer :contract_rvd_win_dropin
      t.integer :contract_rvd_win
      t.integer :job_rvd
      t.integer :level_rvd1
      t.integer :level_rvd2
      t.integer :job_brb
      t.integer :level_brb
      t.integer :contract_brb_win
      t.integer :contract_brb_win_dropin
      t.integer :contract_brb_fail
      t.integer :info_playing_vr
      t.integer :cac_3_stats
      t.integer :cac_7_stats
      t.integer :cac_34_stats
      t.integer :cac_35_stats
      t.integer :job_des
      t.integer :job_tag
      t.integer :level_des
      t.integer :level_tag
      t.integer :contract_des_win
      t.integer :contract_des_win_dropin
      t.integer :contract_des_fail
      t.integer :contract_tag_win
      t.integer :contract_tag_win_dropin
      t.integer :contract_tag_fail
      t.integer :enemy_kills_mute_security_undominatable
      t.integer :pdth
      t.integer :tester
      t.integer :bph_9_stat
      t.integer :uno_puzzle_door_activated
      t.integer :specialization_used_21
      t.integer :level_bph
      t.integer :level_nmh
      t.integer :level_sah
      t.integer :level_skm_mus
      t.integer :level_skm_red2
      t.integer :level_skm_run
      t.integer :level_skm_watchdogs_stage2
      t.integer :level_vit
      t.integer :job_bph
      t.integer :job_nmh
      t.integer :job_sah
      t.integer :job_skm_mus
      t.integer :job_skm_red2
      t.integer :job_skm_run
      t.integer :job_skm_watchdogs_stage2
      t.integer :job_vit
      t.integer :contract_bph_win
      t.integer :contract_bph_win_dropin
      t.integer :contract_bph_fail
      t.integer :contract_nmh_win
      t.integer :contract_nmh_win_dropin
      t.integer :contract_nmh_fail
      t.integer :contract_sah_win
      t.integer :contract_sah_win_dropin
      t.integer :contract_sah_fail
      t.integer :contract_skm_mus_win
      t.integer :contract_skm_mus_win_dropin
      t.integer :contract_skm_mus_fail
      t.integer :contract_skm_red2_win
      t.integer :contract_skm_red2_win_dropin
      t.integer :contract_skm_red2_fail
      t.integer :contract_skm_run_win
      t.integer :contract_skm_run_win_dropin
      t.integer :contract_skm_run_fail
      t.integer :contract_skm_watchdogs_stage2_win
      t.integer :contract_skm_watchdogs_stage2_win_dropin
      t.integer :contract_skm_watchdogs_stage2_fail
      t.integer :contract_vit_win
      t.integer :contract_vit_win_dropin
      t.integer :contract_vit_fail
      t.integer :character_used_joy
      t.integer :enemy_kills_shadow_spooc
      t.integer :enemy_kills_melee_box
      t.integer :enemy_kills_tank_medic
      t.integer :enemy_kills_tank_mini
      t.integer :enemy_kills_escort_cfo
      t.integer :enemy_kills_captain
      t.integer :enemy_kills_heavy_swat_sniper
      t.integer :job_escape_cafe
      t.integer :contract_escape_cafe_win
      t.integer :contract_escape_cafe_win_dropin
      t.integer :contract_escape_cafe_fail
      t.integer :job_escape_park
      t.integer :contract_escape_park_win
      t.integer :contract_escape_park_win_dropin
      t.integer :contract_escape_park_fail
      t.integer :job_escape_street
      t.integer :contract_escape_street_win
      t.integer :contract_escape_street_fail
      t.integer :job_escape_overpass
      t.integer :contract_escape_overpass_win
      t.integer :contract_escape_overpass_win_dropin
      t.integer :contract_escape_overpass_fail
      t.integer :job_escape_garage
      t.integer :contract_escape_garage_win
      t.integer :contract_escape_garage_win_dropin
      t.integer :contract_escape_garage_fail
      t.integer :level_dream
      t.integer :job_dream
      t.integer :contract_dream_win
      t.integer :contract_dream_win_dropin
      t.integer :contract_dream_fail
      t.integer :level_lucid
      t.integer :job_lucid
      t.integer :contract_lucid_win
      t.integer :contract_lucid_win_dropin
      t.integer :contract_lucid_fail
      t.integer :level_mex
      t.integer :level_mex_cooking
      t.integer :job_mex
      t.integer :job_mex_cooking
      t.integer :contract_mex_win
      t.integer :contract_mex_win_dropin
      t.integer :contract_mex_fail
      t.integer :contract_mex_cooking_win
      t.integer :contract_mex_cooking_win_dropin
      t.integer :contract_mex_cooking_fail
      t.integer :enemy_kills_bolivian_indoors_mex
      t.integer :equipped_suit
      t.integer :level_bex
      t.integer :job_bex
      t.integer :contract_bex_win_dropin
      t.integer :contract_bex_fail
      t.integer :enemy_kills_security_mex
      t.integer :enemy_kills_swat_turret
      t.integer :enemy_kills_civilian_mariachi
      t.integer :contract_bex_win
      t.integer :level_skm_bex
      t.integer :level_skm_cas
      t.integer :job_skm_bex
      t.integer :job_skm_cas
      t.integer :contract_skm_arena_win
      t.integer :contract_skm_arena_fail
      t.integer :contract_skm_bex_win_dropin
      t.integer :contract_skm_bex_fail
      t.integer :contract_skm_big2_win_dropin
      t.integer :contract_skm_big2_fail
      t.integer :contract_skm_cas_win
      t.integer :contract_skm_cas_win_dropin
      t.integer :contract_skm_mallcrasher_win
      t.integer :contract_skm_mallcrasher_win_dropin
      t.integer :gloves_used_heist_clown
      t.integer :gloves_used_rainbow_mittens
      t.integer :gloves_used_sneak
      t.integer :level_skm_arena
      t.integer :level_skm_big2
      t.integer :job_pex
      t.integer :job_skm_big2
      t.integer :job_skm_mallcrasher
      t.integer :contract_pex_win
      t.integer :contract_pex_win_dropin
      t.integer :contract_pex_fail
      t.integer :contract_skm_bex_win
      t.integer :contract_skm_big2_win
      t.integer :contract_skm_cas_fail
      t.integer :contract_skm_mallcrasher_fail
      t.integer :gloves_used_heist_default
      t.integer :gloves_used_mariatchi
      t.integer :gloves_used_murky
      t.integer :gloves_used_heat
      t.integer :gloves_used_saints
      t.integer :gloves_used_bonemittens
      t.integer :gloves_used_desperado
      t.integer :gloves_used_punk
      t.integer :equipped_glove_id
      t.integer :level_fex
      t.integer :level_pex
      t.integer :level_skm_mallcrasher
      t.integer :job_fex
      t.integer :job_skm_arena
      t.integer :contract_fex_win_dropin
      t.integer :contract_fex_fail
      t.integer :contract_skm_arena_win_dropin
      t.integer :gloves_used_default
      t.integer :gloves_used_continental
      t.integer :gloves_used_tiger_neon
      t.integer :gloves_used_tiger_red
      t.integer :gloves_used_esport
      t.integer :gloves_used_bananabike
      t.integer :gloves_used_biker
      t.integer :gloves_used_biker_blue
      t.integer :gloves_used_biker_orange
      t.integer :gloves_used_biker_red
      t.integer :gloves_used_chopper
      t.integer :gloves_used_driver
      t.integer :gloves_used_fancy
      t.integer :gloves_used_hockey
      t.integer :gloves_used_kids
      t.integer :gloves_used_sportsbike
      t.integer :gloves_used_tactical
      t.integer :gloves_used_tiger
      t.integer :gloves_used_neoncity
      t.integer :gloves_used_cosmos
      t.integer :gloves_used_molten
      t.integer :join_stinger_used_0
      t.integer :join_stinger_used_1
      t.integer :join_stinger_used_2
      t.integer :join_stinger_used_3
      t.integer :join_stinger_used_4
      t.integer :join_stinger_used_5
      t.integer :join_stinger_used_6
      t.integer :join_stinger_used_7
      t.integer :join_stinger_used_8
      t.integer :join_stinger_used_9
      t.integer :join_stinger_used_10
      t.integer :join_stinger_used_11
      t.integer :join_stinger_used_12
      t.integer :join_stinger_used_13
      t.integer :join_stinger_used_14
      t.integer :join_stinger_used_15
      t.integer :join_stinger_used_16
      t.integer :join_stinger_used_17
      t.integer :enemy_kills_security_mex_no_pager
      t.integer :equipped_join_stinger
      t.integer :setting_roman_rank_on
      t.integer :setting_roman_rank_off
      t.integer :setting_roman_card_on
      t.integer :setting_roman_card_off
      t.integer :contract_fex_win
      t.integer :gloves_used_silver
      t.integer :join_stinger_used_18
      t.integer :join_stinger_used_19
      t.integer :join_stinger_used_24
      t.integer :join_stinger_used_26
      t.integer :gloves_used_wool
      t.integer :join_stinger_used_20
      t.integer :join_stinger_used_21
      t.integer :join_stinger_used_22
      t.integer :join_stinger_used_23
      t.integer :join_stinger_used_25
      t.integer :gsu
      t.integer :level_chas
      t.integer :job_chas
      t.integer :contract_chas_win
      t.integer :contract_chas_win_dropin
      t.integer :contract_chas_fail
      t.integer :gloves_used_redstripe
      t.integer :gloves_used_flame
      t.integer :gloves_used_reddragon
      t.integer :gloves_used_blackdragon
      t.integer :enemy_kills_triad
      t.integer :gsu_stat
      t.integer :gloves_used_goldnet
      t.integer :gloves_used_postmoto
      t.integer :join_stinger_used_27
      t.integer :join_stinger_used_28
      t.integer :join_stinger_used_29
      t.integer :join_stinger_used_30
      t.integer :join_stinger_used_31
      t.integer :join_stinger_used_32
      t.integer :join_stinger_used_33
      t.integer :join_stinger_used_34
      t.integer :join_stinger_used_35
      t.integer :sawp_stat
      t.integer :equipped_gloves
      t.integer :main_menu_crimenet
      t.integer :main_menu_crimenet_offline
      t.integer :main_menu_story_missions
      t.integer :main_menu_inventory
      t.integer :main_menu_steam_inventory
      t.integer :main_menu_gamehub
      t.integer :main_menu_quit
      t.integer :level_sand
      t.integer :job_sand
      t.integer :contract_sand_win
      t.integer :contract_sand_win_dropin
      t.integer :contract_sand_fail
      t.integer :gloves_used_techhigh_bird
      t.integer :gloves_used_techhigh_dragon
      t.integer :gloves_used_techhigh_tiger
      t.integer :gloves_used_techhigh_tortoise
      t.integer :gloves_used_techlow_bird
      t.integer :gloves_used_techlow_dragon
      t.integer :gloves_used_techlow_tiger
      t.integer :gloves_used_techlow_tortoise
      t.integer :story_menu_skip
      t.integer :main_menu_options
      t.integer :main_menu_achievements
      t.integer :main_menu_fbi_files
      t.integer :pda_stat_a
      t.integer :pda_stat_b
      t.integer :pda_stat_c
      t.integer :pda_stat_d
      t.integer :gloves_used_jesterstripe
      t.integer :level_chca
      t.integer :job_chca
      t.integer :contract_chca_win
      t.integer :contract_chca_win_dropin
      t.integer :contract_chca_fail
      t.integer :gloves_used_mnk
      t.integer :gloves_used_mnt
      t.integer :gloves_used_tgr
      t.integer :gloves_used_vpr
      t.integer :balloons_popped
      t.integer :enemy_kills_civilian_no_penalty
      t.integer :gloves_used_overkillpunk
      t.integer :specialization_used_22
      t.integer :dec21_02_stat
      t.integer :level_pent
      t.integer :job_pent
      t.integer :contract_pent_win
      t.integer :contract_pent_win_dropin
      t.integer :contract_pent_fail
      t.integer :gloves_used_biker_red_led
      t.integer :gloves_used_biker_yellow_led
      t.integer :gloves_used_dragonscale
      t.integer :gloves_used_spikeknuckle
      t.integer :enemy_kills_triad_boss
      t.integer :enemy_kills_triad_boss_no_armor
      t.integer :gloves_used_blackstar
      t.integer :gloves_used_hardwork
      t.integer :gloves_used_texriding
      t.integer :gloves_used_workranch
      t.integer :pxp1_1_stats
      t.integer :ranc_9_stat
      t.integer :ranc_11_stat
      t.integer :enemy_kills_marshal_marksman
      t.integer :gloves_used_darkmat
      t.integer :gloves_used_ranchdiesel
      t.integer :level_ranc
      t.integer :job_ranc
      t.integer :contract_ranc_win
      t.integer :contract_ranc_win_dropin
      t.integer :contract_ranc_fail
      t.integer :gloves_used_chromecross
      t.integer :gloves_used_redhand
      t.integer :enemy_kills_ranchmanager
      t.integer :pda_9_stat_a
      t.integer :pda_9_stat_b
      t.integer :pda_9_stat_c
      t.integer :pda_9_stat_d
      t.integer :pda_9_stat_a_test
      t.integer :pda_9_stat_b_test
      t.integer :pda_9_stat_c_test
      t.integer :pda_9_stat_d_test
      t.integer :gloves_used_leatherspark
      t.integer :gloves_used_dodskull
      t.integer :job_trai
      t.integer :level_trai
      t.integer :contract_trai_win
      t.integer :contract_trai_win_dropin
      t.integer :contract_trai_fail
      t.integer :pxp2_1_stats
      t.integer :pxp2_2_stats
      t.integer :pxp2_3_stats
      t.integer :gloves_used_railwork
      t.integer :enemy_kills_marshal_shield
      t.integer :join_stinger_used_36
      t.integer :gloves_used_tornrags
      t.integer :gloves_used_tasslefringe
      t.integer :gloves_used_devilclaws
      t.integer :marshal_shield_break
      t.integer :specialization_used_23
      t.integer :enemy_kills_snowman_boss
      t.integer :enemy_kills_marshal_shield_break
      t.integer :gadget_used_grenade_crate
      t.integer :corp_10_stats
      t.integer :level_corp
      t.integer :job_corp
      t.integer :contract_corp_win
      t.integer :contract_corp_win_dropin
      t.integer :contract_corp_fail
      t.integer :gloves_used_beigedriver
      t.integer :gloves_used_txbull
      t.integer :gloves_used_txrider
      t.integer :gloves_used_txrivet
      t.integer :gloves_used_txsuede
      t.timestamps
    end
  end
end
